
import type { Product, Category } from './types';
import { PlaceHolderImages } from './placeholder-images';
import { Shirt, Laptop, Watch, Dna, Footprints, Layers, Smartphone, Link as LinkIcon, Palette } from 'lucide-react';

const findImage = (id: string) => {
  const image = PlaceHolderImages.find(img => img.id === id);
  if (!image) {
    // Return a default placeholder if no image is found
    return { url: 'https://placehold.co/600x400', hint: 'placeholder' };
  }
  return { url: image.imageUrl, hint: image.imageHint };
};

export const categories: Category[] = [
  { id: 'cat1', name: 'Clothes', icon: Shirt },
  { id: 'cat2', name: 'Wigs', icon: Dna },
  { id: 'cat3', name: 'Laptops', icon: Laptop },
  { id: 'cat4', name: 'Shoes', icon: Footprints },
  { id: 'cat5', name: 'Watches', icon: Watch },
  { id: 'cat6', name: 'Underwear', icon: Layers },
  { id: 'cat7', name: 'Chains', icon: LinkIcon },
  { id: 'cat8', name: 'Phones', icon: Smartphone },
  { id: 'cat9', name: 'Beauty', icon: Palette },
];

export const brands: string[] = ['Zenco', 'Stellar', 'Nexa', 'Orion', 'Helios', 'iDino', 'Aperture', 'Denim Edge', 'Alpine Ridge', 'Velocity', 'Tempo', 'Zenith', 'SilkFlow', 'Eon', 'Nova', 'Crimson', 'Eco', 'Stride', 'Vivid', 'Chrono'];

export const products: Product[] = [
  {
    id: 'prod_1',
    slug: 'stellar-sovereign-18k-chronograph',
    name: 'Stellar Sovereign 18k Chronograph',
    description: 'Command the moment. The Sovereign is a masterpiece of 18k gold and precision engineering, built for those who lead. A statement of pure, undiluted power.',
    category: 'Watches',
    price: 3199.00,
    brand: 'Stellar',
    images: [findImage('prod_img_1')],
    stock: 10,
    rating: 4.9,
    reviewCount: 198
  },
  {
    id: 'prod_2',
    slug: 'helios-apex-titanium-chrono',
    name: 'Helios Apex Titanium Chrono',
    description: 'Master time itself. Fusing aerospace-grade titanium with classic functionality, the Apex is the essential tool for the modern pioneer who values both style and substance.',
    category: 'Watches',
    price: 2250.00,
    brand: 'Helios',
    images: [findImage('prod_img_2')],
    stock: 18,
    rating: 4.8,
    reviewCount: 154
  },
  {
    id: 'prod_3',
    slug: 'zenco-zephyrblade-ultrabook',
    name: 'Zenco ZephyrBlade Ultrabook',
    description: 'Unleash your potential. Impossibly sleek and astonishingly powerful, the ZephyrBlade packs immense performance for seamless creativity and entertainment, wherever inspiration strikes.',
    category: 'Laptops',
    price: 1799.99,
    brand: 'Zenco',
    images: [findImage('prod_img_3')],
    stock: 11,
    rating: 4.9,
    reviewCount: 281
  },
  {
    id: 'prod_4',
    slug: 'nexa-vanguard-pro-x-laptop',
    name: 'Nexa Vanguard Pro-X Laptop',
    description: 'Lead the charge. The Vanguard Pro-X is engineered with next-gen performance and a breathtaking 4K display, making it the ultimate machine for professionals who demand nothing but the best.',
    category: 'Laptops',
    price: 2499.00,
    brand: 'Nexa',
    images: [findImage('prod_img_4')],
    stock: 9,
    rating: 5.0,
    reviewCount: 215
  },
  {
    id: 'prod_5',
    slug: 'orion-supima-heritage-tee',
    name: 'Orion Supima Heritage Tee',
    description: 'Rediscover a legend. The Orion Supima Heritage Tee is the cornerstone of any refined wardrobe, offering a sublimely soft feel and a fit so perfect, you’ll need one in every color.',
    category: 'Clothes',
    price: 75.00,
    brand: 'Orion',
    images: [findImage('prod_img_5')],
    stock: 250,
    rating: 4.7,
    reviewCount: 410
  },
  {
    id: 'prod_6',
    slug: 'stellar-propulsion-runners',
    name: 'Stellar Propulsion Runners',
    description: 'Elevate every stride. Meticulously engineered for peak athletic performance and unparalleled comfort, the Propulsion Runners will carry you across any finish line.',
    category: 'Shoes',
    price: 225.00,
    brand: 'Stellar',
    images: [findImage('prod_img_6')],
    stock: 50,
    rating: 4.8,
    reviewCount: 212
  },
  {
    id: 'prod_7',
    slug: 'zenco-artisan-selvedge-denim',
    name: 'Zenco Artisan Selvedge Denim',
    description: 'The definitive denim. Zenco Artisan Selvedge Jeans blend timeless style with modern comfort, crafted from premium Japanese denim for a fit that feels custom-made and ages beautifully.',
    category: 'Clothes',
    price: 219.99,
    brand: 'Zenco',
    images: [findImage('prod_img_7')],
    stock: 60,
    rating: 4.9,
    reviewCount: 295
  },
  {
    id: 'prod_8',
    slug: 'helios-riviera-leather-loafers',
    name: 'Helios Riviera Leather Loafers',
    description: 'Walk with unmatched confidence. The Helios Riviera Loafers embody effortless sophistication, crafted from the finest Italian leather to provide sublime comfort from the boardroom to the riviera.',
    category: 'Shoes',
    price: 320.00,
    brand: 'Helios',
    images: [findImage('prod_img_8')],
    stock: 42,
    rating: 4.9,
    reviewCount: 160
  },
  {
    id: 'prod_9',
    slug: 'nexa-horizon-x1-pro-phone',
    name: 'Nexa-Horizon X1 Pro Phone',
    description: 'Experience tomorrow, today. The Horizon X1 Pro puts the future in your palm with its revolutionary edge-to-edge display and a cinematic-grade camera that captures life in breathtaking detail.',
    category: 'Phones',
    price: 1599.00,
    brand: 'Nexa',
    images: [findImage('prod_img_9')],
    stock: 35,
    rating: 4.9,
    reviewCount: 520
  },
  {
    id: 'prod_10',
    slug: 'aperture-sun-kissed-blonde-wig',
    name: 'Aperture Sun-Kissed Blonde Wig',
    description: 'Instantly transform your style. Expertly crafted from heat-resistant fibers, the Sun-Kissed Wig offers a stunningly natural look and feel that’s sure to turn heads.',
    category: 'Wigs',
    price: 139.99,
    brand: 'Aperture',
    images: [findImage('prod_img_10')],
    stock: 25,
    rating: 4.7,
    reviewCount: 105
  },
  {
    id: 'prod_11',
    slug: 'stellar-midnight-gala-gown',
    name: 'Stellar Midnight Gala Gown',
    description: 'Command the night in this exquisite garment for life’s most memorable moments. Its elegant silhouette and sparkling details ensure you are the center of every eye.',
    category: 'Clothes',
    price: 649.00,
    brand: 'Stellar',
    images: [findImage('prod_img_11')],
    stock: 15,
    rating: 5.0,
    reviewCount: 68
  },
  {
    id: 'prod_12',
    slug: 'orion-scarlet-stiletto-heels',
    name: 'Orion Scarlet Stiletto Heels',
    description: 'Ignite your look with a statement of confidence and raw glamour. These heels are designed for maximum visual impact while providing surprising comfort.',
    category: 'Shoes',
    price: 279.50,
    brand: 'Orion',
    images: [findImage('prod_img_12')],
    stock: 40,
    rating: 4.8,
    reviewCount: 115
  },
  {
    id: 'prod_13',
    slug: 'nexa-sterling-herringbone-chain',
    name: 'Nexa Sterling Herringbone Chain',
    description: 'Subtle elegance, perfected. This versatile and delicate masterpiece is perfect for adding a touch of refined class to both day and evening wear.',
    category: 'Chains',
    price: 410.00,
    brand: 'Nexa',
    images: [findImage('prod_img_13')],
    stock: 70,
    rating: 4.7,
    reviewCount: 165
  },
  {
    id: 'prod_14',
    slug: 'zenco-cloud-comfort-modal-briefs',
    name: 'Zenco Cloud-Comfort Modal Briefs',
    description: 'Experience a new realm of comfort. Made from exceptionally soft modal fabric, they provide all-day support and a barely-there feel for ultimate luxury.',
    category: 'Underwear',
    price: 45.00,
    brand: 'Zenco',
    images: [findImage('prod_img_14')],
    stock: 180,
    rating: 4.9,
    reviewCount: 310
  },
  {
    id: 'prod_15',
    slug: 'helios-chestnut-elegance-wig',
    name: 'Helios Chestnut Elegance Wig',
    description: 'Embrace a new you. Featuring rich, multi-tonal color and a luxuriously soft texture, it provides a look of natural elegance and charm for any occasion.',
    category: 'Wigs',
    price: 169.00,
    brand: 'Helios',
    images: [findImage('prod_img_15')],
    stock: 20,
    rating: 4.8,
    reviewCount: 95
  },
  {
    id: 'prod_16',
    slug: 'aperture-predator-x-gaming-laptop',
    name: 'Aperture Predator-X Gaming Laptop',
    description: 'Conquer any virtual world. Engineered for elite-level gaming, it features a 240Hz screen and blistering processing power for an immersive, zero-lag experience.',
    category: 'Laptops',
    price: 2799.00,
    brand: 'Aperture',
    images: [findImage('prod_img_16')],
    stock: 8,
    rating: 5.0,
    reviewCount: 190
  },
  {
    id: 'prod_17',
    slug: 'stellar-nimbus-luxe-fleece-hoodie',
    name: 'Stellar Nimbus Luxe Fleece Hoodie',
    description: 'Wrap yourself in pure warmth. Incredibly soft and stylishly designed, the Nimbus is the perfect companion for cool evenings or relaxing in ultimate comfort.',
    category: 'Clothes',
    price: 160.00,
    brand: 'Stellar',
    images: [findImage('prod_img_17')],
    stock: 45,
    rating: 4.9,
    reviewCount: 220
  },
  {
    id: 'prod_18',
    slug: 'orion-heritage-automatic-watch',
    name: 'Orion Heritage Automatic Watch',
    description: 'Embrace tradition with the Orion Heritage. A tribute to timeless horology and reliable mechanics, this automatic watch is an essential, sophisticated accessory.',
    category: 'Watches',
    price: 1950.00,
    brand: 'Orion',
    images: [findImage('prod_img_18')],
    stock: 30,
    rating: 4.8,
    reviewCount: 145
  },
  {
    id: 'prod_19',
    slug: 'zenco-ranger-artisan-leather-boots',
    name: 'Zenco Ranger Artisan Leather Boots',
    description: 'Adventure calls. Built for durability, style, and all-day comfort, these boots are ready to take you from urban jungles to rugged trails without missing a beat.',
    category: 'Shoes',
    price: 385.00,
    brand: 'Zenco',
    images: [findImage('prod_img_19')],
    stock: 28,
    rating: 4.8,
    reviewCount: 175
  },
  {
    id: 'prod_20',
    slug: 'helios-emperor-24k-gold-chain',
    name: 'Helios Emperor 24k Gold Chain',
    description: 'Exude sheer power and luxury. Meticulously crafted from solid 24k gold for a bold feel, this piece is the ultimate statement of success and high fashion.',
    category: 'Chains',
    price: 1350.00,
    brand: 'Helios',
    images: [findImage('prod_img_20')],
    stock: 25,
    rating: 5.0,
    reviewCount: 105
  },
  {
    id: 'prod_21',
    slug: 'idino-smart-watch-series-8',
    name: 'iDino Smart Watch - Series 8',
    description: 'Stay connected and track your fitness with the sleek and powerful iDino Smart Watch. Features a vibrant display and long-lasting battery life.',
    category: 'Watches',
    price: 499.00,
    brand: 'iDino',
    images: [findImage('prod_img_21')],
    stock: 80,
    rating: 4.7,
    reviewCount: 650
  },
  {
    id: 'prod_22',
    slug: 'moissanite-diamond-cuban-necklace',
    name: 'Iced Moissanite Diamond Cuban Necklace',
    description: 'An undeniable statement piece. This heavy Cuban link necklace is fully iced-out with flawless moissanite diamonds for an unmatched sparkle.',
    category: 'Chains',
    price: 2100.00,
    brand: 'Stellar',
    images: [findImage('prod_img_22')],
    stock: 15,
    rating: 5.0,
    reviewCount: 85
  },
  {
    id: 'prod_23',
    slug: 'nexa-core-black-tee',
    name: 'Nexa Core Black Tee',
    description: 'The perfect foundation for any outfit. Our Core Tee is made from premium, ultra-soft cotton for a comfortable, flattering fit that lasts.',
    category: 'Clothes',
    price: 65.00,
    brand: 'Nexa',
    images: [findImage('prod_img_23')],
    stock: 300,
    rating: 4.8,
    reviewCount: 550
  },
  {
    id: 'prod_24',
    slug: 'aperture-pullover-hoodie-cobalt',
    name: 'Aperture Pullover Hoodie - Cobalt',
    description: 'A modern essential. This pullover hoodie in a striking cobalt blue is crafted from plush fleece for ultimate warmth and style.',
    category: 'Clothes',
    price: 130.00,
    brand: 'Aperture',
    images: [findImage('prod_img_24')],
    stock: 80,
    rating: 4.7,
    reviewCount: 210
  },
  {
    id: 'prod_25',
    slug: 'idino-phone-pro-max',
    name: 'iDino Phone Pro Max',
    description: 'Capture your world in stunning detail. The iDino Phone Pro Max features a professional-grade camera system and a brilliant Super Retina display.',
    category: 'Phones',
    price: 1199.00,
    brand: 'iDino',
    images: [findImage('prod_img_25')],
    stock: 40,
    rating: 4.9,
    reviewCount: 780
  },
  {
    id: 'prod_477',
    slug: 'crimson-legacy-watch-477',
    name: 'Crimson Legacy Watch',
    description: 'Embrace timeless elegance with the Crimson Legacy Watch, a testament to classic design and modern craftsmanship. This exquisite timepiece is perfect for any occasion, blending sophistication with reliability.',
    category: 'Watches',
    price: 1850.99,
    brand: 'Crimson',
    images: [ findImage('prod_img_477') ],
    stock: 25,
    rating: 4.8,
    reviewCount: 130
  },
  {
    id: 'prod_478',
    slug: 'silkflow-pro-laptop-478',
    name: 'SilkFlow Pro Laptop',
    description: 'Experience seamless performance with the SilkFlow Pro Laptop. Designed for professionals, it combines a sleek aesthetic with powerful internals to handle any task with ease.',
    category: 'Laptops',
    price: 2100.0,
    brand: 'SilkFlow',
    images: [ findImage('prod_img_447') ],
    stock: 18,
    rating: 4.9,
    reviewCount: 190
  },
  {
    id: 'prod_479',
    slug: 'zenith-summit-boots-479',
    name: 'Zenith Summit Boots',
    description: 'Conquer any terrain with the Zenith Summit Boots. Built for durability and comfort, these boots provide excellent support and traction for all your outdoor adventures.',
    category: 'Shoes',
    price: 280.5,
    brand: 'Zenith',
    images: [ findImage('prod_img_448') ],
    stock: 40,
    rating: 4.7,
    reviewCount: 160
  },
  {
    id: 'prod_480',
    slug: 'tempo-legacy-watch-480',
    name: 'Tempo Legacy Watch',
    description: 'A tribute to timeless design, the Tempo Legacy Watch offers a classic look with modern reliability. The perfect accessory for both formal and casual settings.',
    category: 'Watches',
    price: 950.0,
    brand: 'Tempo',
    images: [ findImage('prod_img_449') ],
    stock: 35,
    rating: 4.6,
    reviewCount: 140
  },
  {
    id: 'prod_481',
    slug: 'alpine-ridge-base-layer-briefs-481',
    name: 'Alpine Ridge Base-Layer Briefs',
    description: 'Stay comfortable and supported with Alpine Ridge Base-Layer Briefs. Made from a moisture-wicking fabric, they are ideal for active lifestyles.',
    category: 'Underwear',
    price: 35.0,
    brand: 'Alpine Ridge',
    images: [ findImage('prod_img_450') ],
    stock: 120,
    rating: 4.8,
    reviewCount: 250
  },
  {
    id: 'prod_482',
    slug: 'denim-edge-anchor-chain-482',
    name: 'Denim Edge Anchor Chain',
    description: 'Add a touch of rugged sophistication with the Denim Edge Anchor Chain. This sterling silver piece is a versatile addition to any jewelry collection.',
    category: 'Chains',
    price: 180.0,
    brand: 'Denim Edge',
    images: [ findImage('prod_img_451') ],
    stock: 60,
    rating: 4.5,
    reviewCount: 90
  },
  {
    id: 'prod_483',
    slug: 'stride-impulse-phone-483',
    name: 'Stride Impulse Phone',
    description: 'Stay ahead with the Stride Impulse Phone. Featuring a fast processor and a stunning display, it’s designed to keep up with your busy life.',
    category: 'Phones',
    price: 899.99,
    brand: 'Stride',
    images: [ findImage('prod_img_452') ],
    stock: 50,
    rating: 4.7,
    reviewCount: 320
  },
  {
    id: 'prod_484',
    slug: 'eco-leaf-print-shirt-484',
    name: 'Eco Leaf-Print Shirt',
    description: 'Embrace nature with the Eco Leaf-Print Shirt. Made from sustainable materials, this shirt features a stylish design that’s perfect for a casual day out.',
    category: 'Clothes',
    price: 85.0,
    brand: 'Eco',
    images: [ findImage('prod_img_453') ],
    stock: 90,
    rating: 4.6,
    reviewCount: 180
  },
  {
    id: 'prod_485',
    slug: 'vivid-fire-opal-wig-485',
    name: 'Vivid Fire Opal Wig',
    description: 'Make a bold statement with the Vivid Fire Opal Wig. Its vibrant colors and high-quality synthetic fibers create a look that is both stunning and unique.',
    category: 'Wigs',
    price: 150.0,
    brand: 'Vivid',
    images: [ findImage('prod_img_454') ],
    stock: 22,
    rating: 4.8,
    reviewCount: 75
  },
  {
    id: 'prod_486',
    slug: 'crimson-valor-laptop-486',
    name: 'Crimson Valor Laptop',
    description: 'Unleash your creativity with the Crimson Valor Laptop. Its powerful performance and vibrant display make it the perfect tool for artists and designers.',
    category: 'Laptops',
    price: 1950.0,
    brand: 'Crimson',
    images: [ findImage('prod_img_455') ],
    stock: 12,
    rating: 4.9,
    reviewCount: 150
  },
  {
    id: 'prod_487',
    slug: 'nova-comet-chasers-487',
    name: 'Nova Comet Chasers',
    description: 'Run faster than ever with the Nova Comet Chasers. These futuristic sneakers are designed for speed, providing lightweight comfort and exceptional energy return.',
    category: 'Shoes',
    price: 230.0,
    brand: 'Nova',
    images: [ findImage('prod_img_456') ],
    stock: 65,
    rating: 4.8,
    reviewCount: 220
  },
  {
    id: 'prod_488',
    slug: 'crimson-executive-watch-488',
    name: 'Crimson Executive Watch',
    description: 'A symbol of success, the Crimson Executive Watch combines a bold design with meticulous craftsmanship. Perfect for the modern professional.',
    category: 'Watches',
    price: 1300.0,
    brand: 'Crimson',
    images: [ findImage('prod_img_457') ],
    stock: 28,
    rating: 4.7,
    reviewCount: 110
  },
  {
    id: 'prod_489',
    slug: 'eon-activewear-tights-489',
    name: 'Eon Activewear Tights',
    description: 'Enhance your workout with Eon Activewear Tights. They offer a supportive fit and flexible fabric that moves with you.',
    category: 'Clothes',
    price: 95.0,
    brand: 'Eon',
    images: [ findImage('prod_img_458') ],
    stock: 85,
    rating: 4.6,
    reviewCount: 190
  },
  {
    id: 'prod_490',
    slug: 'zenith-gala-gown-490',
    name: 'Zenith Gala Gown',
    description: 'Dazzle at any formal event with the Zenith Gala Gown. This stunning dress features intricate detailing and a silhouette that exudes elegance and grace.',
    category: 'Clothes',
    price: 720.0,
    brand: 'Zenith',
    images: [ findImage('prod_img_459') ],
    stock: 15,
    rating: 4.9,
    reviewCount: 65
  },
  {
    id: 'prod_491',
    slug: 'velocity-edge-trainers-491',
    name: 'Velocity Edge Trainers',
    description: 'Push your limits with the Velocity Edge Trainers. Designed for high-intensity workouts, they provide the stability and cushioning you need to perform at your best.',
    category: 'Shoes',
    price: 180.0,
    brand: 'Velocity',
    images: [ findImage('prod_img_460') ],
    stock: 70,
    rating: 4.7,
    reviewCount: 240
  },
  {
    id: 'prod_492',
    slug: 'tempo-classic-chronograph-492',
    name: 'Tempo Classic Chronograph',
    description: 'A timeless piece for any collection, the Tempo Classic Chronograph features a sophisticated design and precise timekeeping.',
    category: 'Watches',
    price: 1100.0,
    brand: 'Tempo',
    images: [ findImage('prod_img_461') ],
    stock: 30,
    rating: 4.8,
    reviewCount: 155
  },
  {
    id: 'prod_493',
    slug: 'stride-comfort-fit-boxer-briefs-493',
    name: 'Stride Comfort-Fit Boxer Briefs',
    description: 'Experience all-day comfort with Stride Boxer Briefs. The soft, breathable fabric and supportive fit make them an everyday essential.',
    category: 'Underwear',
    price: 40.0,
    brand: 'Stride',
    images: [ findImage('prod_img_462') ],
    stock: 150,
    rating: 4.9,
    reviewCount: 300
  },
  {
    id: 'prod_494',
    slug: 'eco-earth-tone-chain-494',
    name: 'Eco Earth-Tone Chain',
    description: 'Connect with nature with the Eco Earth-Tone Chain. This unique piece features natural beads and a simple design for a grounded, stylish look.',
    category: 'Chains',
    price: 90.0,
    brand: 'Eco',
    images: [ findImage('prod_img_463') ],
    stock: 75,
    rating: 4.5,
    reviewCount: 115
  },
  {
    id: 'prod_495',
    slug: 'vivid-harmony-phone-495',
    name: 'Vivid Harmony Phone',
    description: 'Express yourself with the Vivid Harmony Phone. Its colorful design and advanced features make it a fun and powerful device for everyday use.',
    category: 'Phones',
    price: 750.0,
    brand: 'Vivid',
    images: [ findImage('prod_img_464') ],
    stock: 55,
    rating: 4.6,
    reviewCount: 280
  },
  {
    id: 'prod_496',
    slug: 'silkflow-petal-sleeve-top-496',
    name: 'SilkFlow Petal-Sleeve Top',
    description: 'Add a touch of feminine charm with the SilkFlow Petal-Sleeve Top. The delicate sleeve detail and soft fabric create an elegant and comfortable blouse.',
    category: 'Clothes',
    price: 110.0,
    brand: 'SilkFlow',
    images: [ findImage('prod_img_465') ],
    stock: 80,
    rating: 4.7,
    reviewCount: 170
  },
  {
    id: 'prod_497',
    slug: 'alpine-ridge-azure-wig-497',
    name: 'Alpine Ridge Azure Wig',
    description: 'Stand out with the Alpine Ridge Azure Wig. This vibrant blue wig is perfect for costumes, parties, or anyone looking to make a colorful statement.',
    category: 'Wigs',
    price: 130.0,
    brand: 'Alpine Ridge',
    images: [ findImage('prod_img_466') ],
    stock: 25,
    rating: 4.6,
    reviewCount: 60
  },
  {
    id: 'prod_498',
    slug: 'denim-edge-performance-laptop-498',
    name: 'Denim Edge Performance Laptop',
    description: 'Power through your workday with the Denim Edge Performance Laptop. It offers robust performance in a stylish package, perfect for the modern professional.',
    category: 'Laptops',
    price: 1600.0,
    brand: 'Denim Edge',
    images: [ findImage('prod_img_467') ],
    stock: 20,
    rating: 4.8,
    reviewCount: 180
  },
  {
    id: 'prod_499',
    slug: 'crimson-peak-hikers-499',
    name: 'Crimson Peak Hikers',
    description: 'Take on the toughest trails with the Crimson Peak Hikers. These durable boots offer superior grip and support for your most demanding adventures.',
    category: 'Shoes',
    price: 250.0,
    brand: 'Crimson',
    images: [ findImage('prod_img_468') ],
    stock: 45,
    rating: 4.9,
    reviewCount: 200
  },
  {
    id: 'prod_500',
    slug: 'nova-voyager-watch-500',
    name: 'Nova Voyager Watch',
    description: 'Designed for the traveler, the Nova Voyager Watch features multiple time zones and a durable build to accompany you on all your journeys.',
    category: 'Watches',
    price: 850.0,
    brand: 'Nova',
    images: [ findImage('prod_img_469') ],
    stock: 40,
    rating: 4.7,
    reviewCount: 165
  },
  {
    id: 'prod_501',
    slug: 'eon-everyday-boxers-501',
    name: 'Eon Everyday Boxers',
    description: 'A staple for any wardrobe, Eon Everyday Boxers are made from soft cotton for maximum comfort and a perfect fit.',
    category: 'Underwear',
    price: 30.0,
    brand: 'Eon',
    images: [ findImage('prod_img_470') ],
    stock: 200,
    rating: 4.8,
    reviewCount: 350
  },
  {
    id: 'prod_502',
    slug: 'zenith-unity-bracelet-502',
    name: 'Zenith Unity Bracelet',
    description: 'Symbolize connection with the Zenith Unity Bracelet. Its interlocking design in sterling silver is both meaningful and stylish.',
    category: 'Chains',
    price: 220.0,
    brand: 'Zenith',
    images: [ findImage('prod_img_471') ],
    stock: 55,
    rating: 4.6,
    reviewCount: 125
  },
  {
    id: 'prod_503',
    slug: 'velocity-connect-pro-phone-503',
    name: 'Velocity Connect Pro Phone',
    description: 'The ultimate tool for productivity, the Velocity Connect Pro Phone offers powerful features and seamless integration with all your devices.',
    category: 'Phones',
    price: 1300.0,
    brand: 'Velocity',
    images: [ findImage('prod_img_472') ],
    stock: 35,
    rating: 4.9,
    reviewCount: 450
  },
  {
    id: 'prod_504',
    slug: 'tempo-linen-trousers-504',
    name: 'Tempo Linen Trousers',
    description: 'Stay cool and stylish with Tempo Linen Trousers. The lightweight fabric and relaxed fit make them perfect for warm weather.',
    category: 'Clothes',
    price: 120.0,
    brand: 'Tempo',
    images: [ findImage('prod_img_473') ],
    stock: 75,
    rating: 4.7,
    reviewCount: 150
  },
  {
    id: 'prod_505',
    slug: 'stride-emerald-wig-505',
    name: 'Stride Emerald Wig',
    description: 'Channel your inner glam with the Stride Emerald Wig. This rich green wig features a long, wavy style for a dramatic and unforgettable look.',
    category: 'Wigs',
    price: 160.0,
    brand: 'Stride',
    images: [ findImage('prod_img_474') ],
    stock: 20,
    rating: 4.7,
    reviewCount: 80
  },
  {
    id: 'prod_506',
    slug: 'eco-terra-laptop-506',
    name: 'Eco Terra Laptop',
    description: 'Work sustainably with the Eco Terra Laptop. Made from recycled materials, it delivers great performance with a smaller environmental footprint.',
    category: 'Laptops',
    price: 1400.0,
    brand: 'Eco',
    images: [ findImage('prod_img_475') ],
    stock: 25,
    rating: 4.8,
    reviewCount: 175
  },
  {
    id: 'prod_507',
    slug: 'vivid-urban-stompers-507',
    name: 'Vivid Urban Stompers',
    description: 'Make a statement with the Vivid Urban Stompers. These bold, platform boots are perfect for those who want to stand out from the crowd.',
    category: 'Shoes',
    price: 210.0,
    brand: 'Vivid',
    images: [ findImage('prod_img_476') ],
    stock: 50,
    rating: 4.6,
    reviewCount: 140
  },
  {
    id: 'prod_508',
    slug: 'crimson-legacy-watch-508',
    name: 'Crimson Legacy Watch',
    description: 'A watch that tells more than time, the Crimson Legacy Watch is a statement of style and sophistication that will be treasured for generations.',
    category: 'Watches',
    price: 1550.0,
    brand: 'Crimson',
    images: [ findImage('prod_img_477') ],
    stock: 20,
    rating: 4.9,
    reviewCount: 145
  },
];
