
import type { Product, Category } from './types';
import { PlaceHolderImages } from './placeholder-images';
import { Shirt, Laptop, Watch, Dna, Footprints, Layers, Smartphone, Link as LinkIcon } from 'lucide-react';

const findImage = (id: string) => {
  const image = PlaceHolderImages.find(img => img.id === id);
  if (!image) {
    // Return a default placeholder if no image is found
    return { url: 'https://placehold.co/600x400', hint: 'placeholder' };
  }
  return { url: image.imageUrl, hint: image.imageHint };
};

export const categories: Category[] = [
  { id: 'cat1', name: 'Clothes', icon: Shirt },
  { id: 'cat2', name: 'Wigs', icon: Dna },
  { id: 'cat3', name: 'Laptops', icon: Laptop },
  { id: 'cat4', name: 'Shoes', icon: Footprints },
  { id: 'cat5', name: 'Watches', icon: Watch },
  { id: 'cat6', name: 'Underwear', icon: Layers },
  { id: 'cat7', name: 'Chains', icon: LinkIcon },
  { id: 'cat8', name: 'Phones', icon: Smartphone },
];

export const brands: string[] = ['Zenco', 'Stellar', 'Nexa', 'Orion', 'Helios', 'iDino', 'Aperture'];

export const products: Product[] = [
  {
    id: 'prod_1',
    slug: 'stellar-gold-watch',
    name: 'Stellar Gold Watch',
    description: 'Experience luxury and precision with the Stellar Gold Watch, a timeless piece for any occasion.',
    category: 'Watches',
    price: 450000,
    brand: 'Stellar',
    images: [findImage('prod_img_1')],
    stock: 15,
    rating: 4.8,
    reviewCount: 120
  },
  {
    id: 'prod_2',
    slug: 'helios-chronograph',
    name: 'Helios Chronograph',
    description: 'The Helios Chronograph combines modern style with classic functionality, perfect for the discerning individual.',
    category: 'Watches',
    price: 320000,
    brand: 'Helios',
    images: [findImage('prod_img_2')],
    stock: 25,
    rating: 4.7,
    reviewCount: 95
  },
  {
    id: 'prod_3',
    slug: 'zenco-ultrabook',
    name: 'Zenco Ultrabook',
    description: 'Sleek, powerful, and light. The Zenco Ultrabook is your perfect partner for work and creativity on the go.',
    category: 'Laptops',
    price: 750000,
    brand: 'Zenco',
    images: [findImage('prod_img_3')],
    stock: 10,
    rating: 4.9,
    reviewCount: 210
  },
  {
    id: 'prod_4',
    slug: 'nexa-pro-laptop',
    name: 'Nexa Pro Laptop',
    description: 'Unleash your professional potential with the Nexa Pro Laptop, featuring top-tier performance and a stunning display.',
    category: 'Laptops',
    price: 850000,
    brand: 'Nexa',
    images: [findImage('prod_img_4')],
    stock: 8,
    rating: 4.9,
    reviewCount: 180
  },
  {
    id: 'prod_5',
    slug: 'orion-cotton-tee',
    name: 'Orion Cotton Tee',
    description: 'A classic wardrobe staple. The Orion Cotton Tee offers unmatched comfort and a perfect fit.',
    category: 'Clothes',
    price: 25000,
    brand: 'Orion',
    images: [findImage('prod_img_5')],
    stock: 100,
    rating: 4.5,
    reviewCount: 300
  },
  {
    id: 'prod_6',
    slug: 'stellar-runners',
    name: 'Stellar Runners',
    description: 'Step up your game with the Stellar Runners. Designed for comfort, performance, and style.',
    category: 'Shoes',
    price: 95000,
    brand: 'Stellar',
    images: [findImage('prod_img_6')],
    stock: 50,
    rating: 4.6,
    reviewCount: 150
  },
  {
    id: 'prod_7',
    slug: 'zenco-denim-jeans',
    name: 'Zenco Denim Jeans',
    description: 'Timeless style meets modern comfort. The Zenco Denim Jeans are crafted for the perfect fit and lasting wear.',
    category: 'Clothes',
    price: 75000,
    brand: 'Zenco',
    images: [findImage('prod_img_7')],
    stock: 60,
    rating: 4.7,
    reviewCount: 200
  },
  {
    id: 'prod_8',
    slug: 'helios-loafers',
    name: 'Helios Loafers',
    description: 'Sophistication and comfort in every step. The Helios Loafers are crafted from premium brown leather.',
    category: 'Shoes',
    price: 120000,
    brand: 'Helios',
    images: [findImage('prod_img_8')],
    stock: 40,
    rating: 4.8,
    reviewCount: 110
  },
  {
    id: 'prod_9',
    slug: 'nexa-phone-x1',
    name: 'Nexa Phone X1',
    description: 'The future in your hands. The Nexa Phone X1 features a stunning display and a powerful camera system.',
    category: 'Phones',
    price: 550000,
    brand: 'Nexa',
    images: [findImage('prod_img_9')],
    stock: 30,
    rating: 4.9,
    reviewCount: 450
  },
  {
    id: 'prod_10',
    slug: 'aperture-blonde-wig',
    name: 'Aperture Blonde Wig',
    description: 'Transform your look with the Aperture Blonde Wig, made from high-quality synthetic fibers for a natural look and feel.',
    category: 'Wigs',
    price: 65000,
    brand: 'Aperture',
    images: [findImage('prod_img_10')],
    stock: 20,
    rating: 4.6,
    reviewCount: 80
  },
  {
    id: 'prod_11',
    slug: 'stellar-evening-gown',
    name: 'Stellar Evening Gown',
    description: 'Make a statement at any formal event with the elegant and breathtaking Stellar Evening Gown.',
    category: 'Clothes',
    price: 250000,
    brand: 'Stellar',
    images: [findImage('prod_img_11')],
    stock: 12,
    rating: 4.9,
    reviewCount: 45
  },
  {
    id: 'prod_12',
    slug: 'orion-red-heels',
    name: 'Orion Red Heels',
    description: 'Turn heads with the vibrant and stylish Orion Red Heels, the perfect accessory for a bold look.',
    category: 'Shoes',
    price: 85000,
    brand: 'Orion',
    images: [findImage('prod_img_12')],
    stock: 35,
    rating: 4.7,
    reviewCount: 90
  },
  {
    id: 'prod_13',
    slug: 'nexa-silver-chain',
    name: 'Nexa Silver Chain',
    description: 'A delicate and versatile piece, the Nexa Silver Chain adds a touch of elegance to any outfit.',
    category: 'Chains',
    price: 55000,
    brand: 'Nexa',
    images: [findImage('prod_img_13')],
    stock: 70,
    rating: 4.6,
    reviewCount: 130
  },
  {
    id: 'prod_14',
    slug: 'zenco-comfort-briefs',
    name: 'Zenco Comfort Briefs',
    description: 'Experience all-day comfort with the soft and breathable Zenco Comfort Briefs.',
    category: 'Underwear',
    price: 15000,
    brand: 'Zenco',
    images: [findImage('prod_img_14')],
    stock: 150,
    rating: 4.8,
    reviewCount: 250
  },
  {
    id: 'prod_15',
    slug: 'helios-brunette-wig',
    name: 'Helios Brunette Wig',
    description: 'Achieve a stunning, natural look with the Helios Brunette Wig, featuring rich color and soft texture.',
    category: 'Wigs',
    price: 70000,
    brand: 'Helios',
    images: [findImage('prod_img_15')],
    stock: 18,
    rating: 4.7,
    reviewCount: 75
  },
  {
    id: 'prod_16',
    slug: 'aperture-gaming-laptop',
    name: 'Aperture Gaming Laptop',
    description: 'Dominate the competition with the Aperture Gaming Laptop, built for high-performance and immersive gameplay.',
    category: 'Laptops',
    price: 1200000,
    brand: 'Aperture',
    images: [findImage('prod_img_16')],
    stock: 7,
    rating: 4.9,
    reviewCount: 150
  },
  {
    id: 'prod_17',
    slug: 'stellar-fleece-hoodie',
    name: 'Stellar Fleece Hoodie',
    description: 'Stay warm and stylish with the ultra-soft Stellar Fleece Hoodie, perfect for chilly days.',
    category: 'Clothes',
    price: 85000,
    brand: 'Stellar',
    images: [findImage('prod_img_17')],
    stock: 45,
    rating: 4.8,
    reviewCount: 180
  },
  {
    id: 'prod_18',
    slug: 'orion-classic-watch',
    name: 'Orion Classic Watch',
    description: 'A timeless design with modern reliability. The Orion Classic Watch is an essential for any collection.',
    category: 'Watches',
    price: 280000,
    brand: 'Orion',
    images: [findImage('prod_img_18')],
    stock: 30,
    rating: 4.7,
    reviewCount: 115
  },
  {
    id: 'prod_19',
    slug: 'zenco-leather-boots',
    name: 'Zenco Leather Boots',
    description: 'Durable, stylish, and comfortable. The Zenco Leather Boots are ready for any adventure.',
    category: 'Shoes',
    price: 150000,
    brand: 'Zenco',
    images: [findImage('prod_img_19')],
    stock: 25,
    rating: 4.8,
    reviewCount: 140
  },
  {
    id: 'prod_20',
    slug: 'helios-gold-chain',
    name: 'Helios Gold Chain',
    description: 'Make a bold statement with the Helios Gold Chain, crafted for a luxurious and powerful look.',
    category: 'Chains',
    price: 180000,
    brand: 'Helios',
    images: [findImage('prod_img_20')],
    stock: 22,
    rating: 4.9,
    reviewCount: 85
  },
  {
    id: 'prod_21',
    slug: 'idino-smart-watch',
    name: 'iDino Smart Watch',
    description: 'Stay connected and track your fitness with the feature-packed iDino Smart Watch.',
    category: 'Watches',
    price: 135000,
    brand: 'iDino',
    images: [findImage('prod_img_21')],
    stock: 40,
    rating: 4.5,
    reviewCount: 220
  },
  {
    id: 'prod_22',
    slug: 'moissanite-diamond-cuban-necklace',
    name: 'Moissanite Diamond Cuban Necklace',
    description: 'An iconic statement piece. This Moissanite Diamond Cuban Necklace brings unparalleled sparkle and style.',
    category: 'Chains',
    price: 1350000,
    brand: 'Aperture',
    images: [findImage('prod_img_22')],
    stock: 5,
    rating: 5.0,
    reviewCount: 75
  },
  {
    id: 'prod_23',
    slug: 'nexa-basic-tee',
    name: 'Nexa Basic Tee',
    description: 'The perfect foundation for any outfit. The Nexa Basic Tee in black is made from soft, durable cotton.',
    category: 'Clothes',
    price: 22000,
    brand: 'Nexa',
    images: [findImage('prod_img_23')],
    stock: 120,
    rating: 4.6,
    reviewCount: 280
  },
  {
    id: 'prod_24',
    slug: 'aperture-pullover-hoodie',
    name: 'Aperture Pullover Hoodie',
    description: 'Your new favorite hoodie. The Aperture Pullover is soft, comfortable, and perfect for everyday wear.',
    category: 'Clothes',
    price: 90000,
    brand: 'Aperture',
    images: [findImage('prod_img_24')],
    stock: 55,
    rating: 4.7,
    reviewCount: 160
  },
  {
    id: 'prod_25',
    slug: 'idino-phone-pro',
    name: 'iDino Phone Pro',
    description: 'Capture life in stunning detail with the iDino Phone Pro, featuring a professional-grade camera and sleek design.',
    category: 'Phones',
    price: 620000,
    brand: 'iDino',
    images: [findImage('prod_img_25')],
    stock: 28,
    rating: 4.8,
    reviewCount: 350
  },
  {
    id: 'prod_26',
    slug: 'stellar-modal-trunks',
    name: 'Stellar Modal Trunks',
    description: 'Luxuriously soft and supportive, the Stellar Modal Trunks redefine everyday comfort.',
    category: 'Underwear',
    price: 18000,
    brand: 'Stellar',
    images: [findImage('prod_img_26')],
    stock: 90,
    rating: 4.9,
    reviewCount: 190
  },
  {
    id: 'prod_27',
    slug: 'orion-ombre-wig',
    name: 'Orion Ombre Wig',
    description: 'A stunning black and red ombre style that is sure to turn heads. Made with heat-resistant fibers.',
    category: 'Wigs',
    price: 85000,
    brand: 'Orion',
    images: [findImage('prod_img_27')],
    stock: 15,
    rating: 4.7,
    reviewCount: 65
  },
  {
    id: 'prod_28',
    slug: 'zenco-oxford-shoes',
    name: 'Zenco Oxford Shoes',
    description: 'The epitome of classic style. The Zenco Oxford Shoes are perfect for formal occasions and professional settings.',
    category: 'Shoes',
    price: 140000,
    brand: 'Zenco',
    images: [findImage('prod_img_28')],
    stock: 30,
    rating: 4.9,
    reviewCount: 105
  },
  {
    id: 'prod_29',
    slug: 'helios-link-necklace',
    name: 'Helios Link Necklace',
    description: 'A chic and modern rose gold link necklace that adds a touch of sophistication to any look.',
    category: 'Chains',
    price: 95000,
    brand: 'Helios',
    images: [findImage('prod_img_29')],
    stock: 40,
    rating: 4.8,
    reviewCount: 88
  },
  {
    id: 'prod_30',
    slug: 'idino-smartphone-white',
    name: 'iDino Smartphone White',
    description: 'Clean, elegant, and powerful. The iDino Smartphone in white offers a premium experience.',
    category: 'Phones',
    price: 490000,
    brand: 'iDino',
    images: [findImage('prod_img_30')],
    stock: 33,
    rating: 4.7,
    reviewCount: 240
  },
  {
    id: 'prod_31',
    slug: 'idino-tablet-ultra',
    name: 'iDino Tablet Ultra',
    description: 'A powerful tablet for work and play.',
    category: 'Laptops',
    price: 280000,
    brand: 'iDino',
    images: [findImage('prod_img_31')],
    stock: 25,
    rating: 4.7,
    reviewCount: 110
  },
  {
    id: 'prod_32',
    slug: 'aperture-leather-wallet',
    name: 'Aperture Leather Wallet',
    description: 'A stylish and durable leather wallet.',
    category: 'Clothes',
    price: 35000,
    brand: 'Aperture',
    images: [findImage('prod_img_32')],
    stock: 80,
    rating: 4.9,
    reviewCount: 95
  },
  {
    id: 'prod_33',
    slug: 'zenco-wireless-earbuds',
    name: 'Zenco Wireless Earbuds',
    description: 'Crystal clear sound on the go.',
    category: 'Phones',
    price: 60000,
    brand: 'Zenco',
    images: [findImage('prod_img_33')],
    stock: 120,
    rating: 4.6,
    reviewCount: 350
  },
  {
    id: 'prod_34',
    slug: 'orion-silk-scarf',
    name: 'Orion Silk Scarf',
    description: 'An elegant silk scarf with a vibrant pattern.',
    category: 'Clothes',
    price: 45000,
    brand: 'Orion',
    images: [findImage('prod_img_34')],
    stock: 60,
    rating: 4.8,
    reviewCount: 70
  },
  {
    id: 'prod_35',
    slug: 'stellar-sunglasses',
    name: 'Stellar Sunglasses',
    description: 'Protect your eyes with these stylish sunglasses.',
    category: 'Clothes',
    price: 55000,
    brand: 'Stellar',
    images: [findImage('prod_img_35')],
    stock: 90,
    rating: 4.7,
    reviewCount: 180
  },
  {
    id: 'prod_36',
    slug: 'nexa-fitness-tracker',
    name: 'Nexa Fitness Tracker',
    description: 'Track your activity and stay motivated.',
    category: 'Watches',
    price: 75000,
    brand: 'Nexa',
    images: [findImage('prod_img_36')],
    stock: 110,
    rating: 4.5,
    reviewCount: 210
  },
  {
    id: 'prod_37',
    slug: 'helios-messenger-bag',
    name: 'Helios Messenger Bag',
    description: 'A durable and spacious bag for all your essentials.',
    category: 'Clothes',
    price: 88000,
    brand: 'Helios',
    images: [findImage('prod_img_37')],
    stock: 45,
    rating: 4.8,
    reviewCount: 130
  },
  {
    id: 'prod_38',
    slug: 'idino-portable-speaker',
    name: 'iDino Portable Speaker',
    description: 'Take your music anywhere with this powerful speaker.',
    category: 'Phones',
    price: 48000,
    brand: 'iDino',
    images: [findImage('prod_img_38')],
    stock: 150,
    rating: 4.6,
    reviewCount: 280
  },
  {
    id: 'prod_39',
    slug: 'aperture-bob-wig',
    name: 'Aperture Bob Wig',
    description: 'A chic and timeless bob wig.',
    category: 'Wigs',
    price: 58000,
    brand: 'Aperture',
    images: [findImage('prod_img_39')],
    stock: 30,
    rating: 4.7,
    reviewCount: 60
  },
  {
    id: 'prod_40',
    slug: 'zenco-canvas-sneakers',
    name: 'Zenco Canvas Sneakers',
    description: 'Comfortable and stylish sneakers for everyday wear.',
    category: 'Shoes',
    price: 62000,
    brand: 'Zenco',
    images: [findImage('prod_img_40')],
    stock: 200,
    rating: 4.5,
    reviewCount: 400
  },
  {
    id: 'prod_41',
    slug: 'orion-diamond-ring',
    name: 'Orion Diamond Ring',
    description: 'A stunning diamond ring for a special occasion.',
    category: 'Chains',
    price: 950000,
    brand: 'Orion',
    images: [findImage('prod_img_41')],
    stock: 10,
    rating: 5.0,
    reviewCount: 30
  },
  {
    id: 'prod_42',
    slug: 'stellar-performance-leggings',
    name: 'Stellar Performance Leggings',
    description: 'High-performance leggings for your workout.',
    category: 'Clothes',
    price: 42000,
    brand: 'Stellar',
    images: [findImage('prod_img_42')],
    stock: 130,
    rating: 4.8,
    reviewCount: 150
  },
  {
    id: 'prod_43',
    slug: 'nexa-smart-thermostat',
    name: 'Nexa Smart Thermostat',
    description: 'Control your home\'s temperature from anywhere.',
    category: 'Laptops',
    price: 110000,
    brand: 'Nexa',
    images: [findImage('prod_img_43')],
    stock: 40,
    rating: 4.9,
    reviewCount: 80
  },
  {
    id: 'prod_44',
    slug: 'helios-cashmere-sweater',
    name: 'Helios Cashmere Sweater',
    description: 'A luxurious and soft cashmere sweater.',
    category: 'Clothes',
    price: 180000,
    brand: 'Helios',
    images: [findImage('prod_img_44')],
    stock: 25,
    rating: 4.9,
    reviewCount: 65
  },
  {
    id: 'prod_45',
    slug: 'idino-drone',
    name: 'iDino Drone',
    description: 'Capture stunning aerial footage with this easy-to-fly drone.',
    category: 'Phones',
    price: 320000,
    brand: 'iDino',
    images: [findImage('prod_img_45')],
    stock: 15,
    rating: 4.7,
    reviewCount: 120
  },
  {
    id: 'prod_46',
    slug: 'aperture-pearl-necklace',
    name: 'Aperture Pearl Necklace',
    description: 'An elegant pearl necklace for a classic look.',
    category: 'Chains',
    price: 150000,
    brand: 'Aperture',
    images: [findImage('prod_img_46')],
    stock: 35,
    rating: 4.8,
    reviewCount: 90
  },
  {
    id: 'prod_47',
    slug: 'zenco-graphic-tee',
    name: 'Zenco Graphic Tee',
    description: 'A stylish graphic tee to express yourself.',
    category: 'Clothes',
    price: 28000,
    brand: 'Zenco',
    images: [findImage('prod_img_47')],
    stock: 180,
    rating: 4.6,
    reviewCount: 250
  },
  {
    id: 'prod_48',
    slug: 'orion-crossbody-bag',
    name: 'Orion Crossbody Bag',
    description: 'A versatile and stylish bag for your daily essentials.',
    category: 'Clothes',
    price: 68000,
    brand: 'Orion',
    images: [findImage('prod_img_48')],
    stock: 55,
    rating: 4.7,
    reviewCount: 115
  },
  {
    id: 'prod_49',
    slug: 'stellar-wool-coat',
    name: 'Stellar Wool Coat',
    description: 'A warm and elegant wool coat for the colder months.',
    category: 'Clothes',
    price: 290000,
    brand: 'Stellar',
    images: [findImage('prod_img_49')],
    stock: 20,
    rating: 4.9,
    reviewCount: 85
  },
  {
    id: 'prod_50',
    slug: 'nexa-smart-lock',
    name: 'Nexa Smart Lock',
    description: 'Secure your home with this keyless smart lock.',
    category: 'Laptops',
    price: 130000,
    brand: 'Nexa',
    images: [findImage('prod_img_50')],
    stock: 30,
    rating: 4.8,
    reviewCount: 100
  }
];
