
import type { Product, Category } from './types';
import { PlaceHolderImages } from './placeholder-images';
import { Shirt, Laptop, Watch, Dna, Footprints, Layers } from 'lucide-react';

const findImage = (id: string) => {
  const image = PlaceHolderImages.find(img => img.id === id);
  if (!image) {
    // Return a default placeholder if no image is found
    return { url: 'https://placehold.co/600x400', hint: 'placeholder' };
  }
  return { url: image.imageUrl, hint: image.imageHint };
};

export const categories: Category[] = [
  { id: 'cat1', name: 'Clothes', icon: Shirt },
  { id: 'cat2', name: 'Wigs', icon: Dna },
  { id: 'cat3', name: 'Laptops', icon: Laptop },
  { id: 'cat4', name: 'Shoes', icon: Footprints },
  { id: 'cat5', name: 'Watches', icon: Watch },
  { id: 'cat6', name: 'Underwear', icon: Layers },
];

export const brands: string[] = ['Zenco', 'Stellar', 'Nexa', 'Orion', 'Helios', 'iDino', 'Aperture'];

export const products: Product[] = [
  {
    id: 'prod_1',
    slug: 'product-1',
    name: 'Assorted Product 1',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Watches',
    price: 167556,
    brand: 'Zenco',
    images: [{ url: findImage('prod_img_1').url, hint: findImage('prod_img_1').hint }],
    stock: 153,
    rating: 4.5,
    reviewCount: 423
  },
  {
    id: 'prod_2',
    slug: 'product-2',
    name: 'Assorted Product 2',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Wigs',
    price: 64809,
    brand: 'Stellar',
    images: [{ url: findImage('prod_img_2').url, hint: findImage('prod_img_2').hint }],
    stock: 147,
    rating: 4.1,
    reviewCount: 398
  },
  {
    id: 'prod_3',
    slug: 'product-3',
    name: 'Assorted Product 3',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Laptops',
    price: 147883,
    brand: 'Nexa',
    images: [{ url: findImage('prod_img_3').url, hint: findImage('prod_img_3').hint }],
    stock: 18,
    rating: 4.2,
    reviewCount: 226
  },
  {
    id: 'prod_4',
    slug: 'product-4',
    name: 'Assorted Product 4',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Shoes',
    price: 19688,
    brand: 'Orion',
    images: [{ url: findImage('prod_img_4').url, hint: findImage('prod_img_4').hint }],
    stock: 122,
    rating: 4.0,
    reviewCount: 231
  },
  {
    id: 'prod_5',
    slug: 'product-5',
    name: 'Assorted Product 5',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Watches',
    price: 110482,
    brand: 'Helios',
    images: [{ url: findImage('prod_img_5').url, hint: findImage('prod_img_5').hint }],
    stock: 196,
    rating: 4.8,
    reviewCount: 366
  },
  {
    id: 'prod_6',
    slug: 'product-6',
    name: 'Assorted Product 6',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Underwear',
    price: 153289,
    brand: 'iDino',
    images: [{ url: findImage('prod_img_6').url, hint: findImage('prod_img_6').hint }],
    stock: 75,
    rating: 4.6,
    reviewCount: 169
  },
  {
    id: 'prod_7',
    slug: 'product-7',
    name: 'Assorted Product 7',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Clothes',
    price: 115637,
    brand: 'Aperture',
    images: [{ url: findImage('prod_img_7').url, hint: findImage('prod_img_7').hint }],
    stock: 32,
    rating: 4.3,
    reviewCount: 466
  },
  {
    id: 'prod_8',
    slug: 'product-8',
    name: 'Assorted Product 8',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Wigs',
    price: 172918,
    brand: 'Zenco',
    images: [{ url: findImage('prod_img_8').url, hint: findImage('prod_img_8').hint }],
    stock: 155,
    rating: 4.1,
    reviewCount: 247
  },
  {
    id: 'prod_9',
    slug: 'product-9',
    name: 'Assorted Product 9',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Laptops',
    price: 139158,
    brand: 'Stellar',
    images: [{ url: findImage('prod_img_9').url, hint: findImage('prod_img_9').hint }],
    stock: 185,
    rating: 4.0,
    reviewCount: 166
  },
  {
    id: 'prod_10',
    slug: 'product-10',
    name: 'Assorted Product 10',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Shoes',
    price: 176162,
    brand: 'Nexa',
    images: [{ url: findImage('prod_img_10').url, hint: findImage('prod_img_10').hint }],
    stock: 82,
    rating: 4.2,
    reviewCount: 301
  },
  {
    id: 'prod_11',
    slug: 'product-11',
    name: 'Assorted Product 11',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Watches',
    price: 52028,
    brand: 'Orion',
    images: [{ url: findImage('prod_img_11').url, hint: findImage('prod_img_11').hint }],
    stock: 143,
    rating: 4.5,
    reviewCount: 181
  },
  {
    id: 'prod_12',
    slug: 'product-12',
    name: 'Assorted Product 12',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Underwear',
    price: 147321,
    brand: 'Helios',
    images: [{ url: findImage('prod_img_12').url, hint: findImage('prod_img_12').hint }],
    stock: 45,
    rating: 4.9,
    reviewCount: 260
  },
  {
    id: 'prod_13',
    slug: 'product-13',
    name: 'Assorted Product 13',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Clothes',
    price: 153096,
    brand: 'iDino',
    images: [{ url: findImage('prod_img_13').url, hint: findImage('prod_img_13').hint }],
    stock: 13,
    rating: 4.7,
    reviewCount: 461
  },
  {
    id: 'prod_14',
    slug: 'product-14',
    name: 'Assorted Product 14',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Wigs',
    price: 74681,
    brand: 'Aperture',
    images: [{ url: findImage('prod_img_14').url, hint: findImage('prod_img_14').hint }],
    stock: 62,
    rating: 4.8,
    reviewCount: 396
  },
  {
    id: 'prod_15',
    slug: 'product-15',
    name: 'Assorted Product 15',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Laptops',
    price: 36737,
    brand: 'Zenco',
    images: [{ url: findImage('prod_img_15').url, hint: findImage('prod_img_15').hint }],
    stock: 89,
    rating: 4.5,
    reviewCount: 417
  },
  {
    id: 'prod_16',
    slug: 'product-16',
    name: 'Assorted Product 16',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Shoes',
    price: 75789,
    brand: 'Stellar',
    images: [{ url: findImage('prod_img_16').url, hint: findImage('prod_img_16').hint }],
    stock: 167,
    rating: 4.6,
    reviewCount: 326
  },
  {
    id: 'prod_17',
    slug: 'product-17',
    name: 'Assorted Product 17',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Watches',
    price: 157978,
    brand: 'Nexa',
    images: [{ url: findImage('prod_img_17').url, hint: findImage('prod_img_17').hint }],
    stock: 67,
    rating: 4.6,
    reviewCount: 161
  },
  {
    id: 'prod_18',
    slug: 'product-18',
    name: 'Assorted Product 18',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Underwear',
    price: 198544,
    brand: 'Orion',
    images: [{ url: findImage('prod_img_18').url, hint: findImage('prod_img_18').hint }],
    stock: 89,
    rating: 4.0,
    reviewCount: 172
  },
  {
    id: 'prod_19',
    slug: 'product-19',
    name: 'Assorted Product 19',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Clothes',
    price: 52332,
    brand: 'Helios',
    images: [{ url: findImage('prod_img_19').url, hint: findImage('prod_img_19').hint }],
    stock: 115,
    rating: 4.1,
    reviewCount: 227
  },
  {
    id: 'prod_20',
    slug: 'product-20',
    name: 'Assorted Product 20',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Wigs',
    price: 147551,
    brand: 'iDino',
    images: [{ url: findImage('prod_img_20').url, hint: findImage('prod_img_20').hint }],
    stock: 45,
    rating: 4.2,
    reviewCount: 350
  },
  {
    id: 'prod_21',
    slug: 'product-21',
    name: 'Assorted Product 21',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Laptops',
    price: 182390,
    brand: 'Aperture',
    images: [{ url: findImage('prod_img_21').url, hint: findImage('prod_img_21').hint }],
    stock: 111,
    rating: 4.1,
    reviewCount: 184
  },
  {
    id: 'prod_22',
    slug: 'product-22',
    name: 'Assorted Product 22',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Shoes',
    price: 118431,
    brand: 'Zenco',
    images: [{ url: findImage('prod_img_22').url, hint: findImage('prod_img_22').hint }],
    stock: 33,
    rating: 4.3,
    reviewCount: 337
  },
  {
    id: 'prod_23',
    slug: 'product-23',
    name: 'Assorted Product 23',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Watches',
    price: 66675,
    brand: 'Stellar',
    images: [{ url: findImage('prod_img_23').url, hint: findImage('prod_img_23').hint }],
    stock: 43,
    rating: 4.4,
    reviewCount: 479
  },
  {
    id: 'prod_24',
    slug: 'product-24',
    name: 'Assorted Product 24',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Underwear',
    price: 76543,
    brand: 'Nexa',
    images: [{ url: findImage('prod_img_24').url, hint: findImage('prod_img_24').hint }],
    stock: 116,
    rating: 4.8,
    reviewCount: 132
  },
  {
    id: 'prod_25',
    slug: 'product-25',
    name: 'Assorted Product 25',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Clothes',
    price: 90623,
    brand: 'Orion',
    images: [{ url: findImage('prod_img_25').url, hint: findImage('prod_img_25').hint }],
    stock: 191,
    rating: 4.8,
    reviewCount: 221
  },
  {
    id: 'prod_26',
    slug: 'product-26',
    name: 'Assorted Product 26',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Wigs',
    price: 18765,
    brand: 'Helios',
    images: [{ url: findImage('prod_img_26').url, hint: findImage('prod_img_26').hint }],
    stock: 187,
    rating: 4.9,
    reviewCount: 228
  },
  {
    id: 'prod_27',
    slug: 'product-27',
    name: 'Assorted Product 27',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Laptops',
    price: 129483,
    brand: 'iDino',
    images: [{ url: findImage('prod_img_27').url, hint: findImage('prod_img_27').hint }],
    stock: 147,
    rating: 4.2,
    reviewCount: 300
  },
  {
    id: 'prod_28',
    slug: 'product-28',
    name: 'Assorted Product 28',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Shoes',
    price: 15632,
    brand: 'Aperture',
    images: [{ url: findImage('prod_img_28').url, hint: findImage('prod_img_28').hint }],
    stock: 184,
    rating: 4.7,
    reviewCount: 168
  },
  {
    id: 'prod_29',
    slug: 'product-29',
    name: 'Assorted Product 29',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Watches',
    price: 52206,
    brand: 'Zenco',
    images: [{ url: findImage('prod_img_29').url, hint: findImage('prod_img_29').hint }],
    stock: 120,
    rating: 4.9,
    reviewCount: 351
  },
  {
    id: 'prod_30',
    slug: 'product-30',
    name: 'Assorted Product 30',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Underwear',
    price: 58826,
    brand: 'Stellar',
    images: [{ url: findImage('prod_img_30').url, hint: findImage('prod_img_30').hint }],
    stock: 141,
    rating: 4.8,
    reviewCount: 227
  },
  {
    id: 'prod_31',
    slug: 'product-31',
    name: 'Assorted Product 31',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Clothes',
    price: 139126,
    brand: 'Nexa',
    images: [{ url: findImage('prod_img_31').url, hint: findImage('prod_img_31').hint }],
    stock: 97,
    rating: 4.3,
    reviewCount: 462
  },
  {
    id: 'prod_32',
    slug: 'product-32',
    name: 'Assorted Product 32',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Wigs',
    price: 177995,
    brand: 'Orion',
    images: [{ url: findImage('prod_img_32').url, hint: findImage('prod_img_32').hint }],
    stock: 146,
    rating: 4.7,
    reviewCount: 304
  },
  {
    id: 'prod_33',
    slug: 'product-33',
    name: 'Assorted Product 33',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Laptops',
    price: 181373,
    brand: 'Helios',
    images: [{ url: findImage('prod_img_33').url, hint: findImage('prod_img_33').hint }],
    stock: 14,
    rating: 4.3,
    reviewCount: 167
  },
  {
    id: 'prod_34',
    slug: 'product-34',
    name: 'Assorted Product 34',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Shoes',
    price: 106093,
    brand: 'iDino',
    images: [{ url: findImage('prod_img_34').url, hint: findImage('prod_img_34').hint }],
    stock: 58,
    rating: 4.9,
    reviewCount: 421
  },
  {
    id: 'prod_35',
    slug: 'product-35',
    name: 'Assorted Product 35',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Watches',
    price: 104277,
    brand: 'Aperture',
    images: [{ url: findImage('prod_img_35').url, hint: findImage('prod_img_35').hint }],
    stock: 108,
    rating: 4.4,
    reviewCount: 153
  },
  {
    id: 'prod_36',
    slug: 'product-36',
    name: 'Assorted Product 36',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Underwear',
    price: 141974,
    brand: 'Zenco',
    images: [{ url: findImage('prod_img_36').url, hint: findImage('prod_img_36').hint }],
    stock: 87,
    rating: 4.1,
    reviewCount: 167
  },
  {
    id: 'prod_37',
    slug: 'product-37',
    name: 'Assorted Product 37',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Clothes',
    price: 139176,
    brand: 'Stellar',
    images: [{ url: findImage('prod_img_37').url, hint: findImage('prod_img_37').hint }],
    stock: 198,
    rating: 4.3,
    reviewCount: 228
  },
  {
    id: 'prod_38',
    slug: 'product-38',
    name: 'Assorted Product 38',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Wigs',
    price: 129758,
    brand: 'Nexa',
    images: [{ url: findImage('prod_img_38').url, hint: findImage('prod_img_38').hint }],
    stock: 45,
    rating: 4.4,
    reviewCount: 412
  },
  {
    id: 'prod_39',
    slug: 'product-39',
    name: 'Assorted Product 39',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Laptops',
    price: 195747,
    brand: 'Orion',
    images: [{ url: findImage('prod_img_39').url, hint: findImage('prod_img_39').hint }],
    stock: 22,
    rating: 4.7,
    reviewCount: 247
  },
  {
    id: 'prod_40',
    slug: 'product-40',
    name: 'Assorted Product 40',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Shoes',
    price: 104523,
    brand: 'Helios',
    images: [{ url: findImage('prod_img_40').url, hint: findImage('prod_img_40').hint }],
    stock: 58,
    rating: 4.4,
    reviewCount: 461
  },
  {
    id: 'prod_41',
    slug: 'product-41',
    name: 'Assorted Product 41',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Watches',
    price: 19379,
    brand: 'iDino',
    images: [{ url: findImage('prod_img_41').url, hint: findImage('prod_img_41').hint }],
    stock: 153,
    rating: 4.5,
    reviewCount: 254
  },
  {
    id: 'prod_42',
    slug: 'product-42',
    name: 'Assorted Product 42',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Underwear',
    price: 66366,
    brand: 'Aperture',
    images: [{ url: findImage('prod_img_42').url, hint: findImage('prod_img_42').hint }],
    stock: 147,
    rating: 4.3,
    reviewCount: 288
  },
  {
    id: 'prod_43',
    slug: 'product-43',
    name: 'Assorted Product 43',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Clothes',
    price: 185850,
    brand: 'Zenco',
    images: [{ url: findImage('prod_img_43').url, hint: findImage('prod_img_43').hint }],
    stock: 53,
    rating: 4.4,
    reviewCount: 301
  },
  {
    id: 'prod_44',
    slug: 'product-44',
    name: 'Assorted Product 44',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Wigs',
    price: 100994,
    brand: 'Stellar',
    images: [{ url: findImage('prod_img_44').url, hint: findImage('prod_img_44').hint }],
    stock: 189,
    rating: 4.0,
    reviewCount: 494
  },
  {
    id: 'prod_45',
    slug: 'product-45',
    name: 'Assorted Product 45',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Laptops',
    price: 125191,
    brand: 'Nexa',
    images: [{ url: findImage('prod_img_45').url, hint: findImage('prod_img_45').hint }],
    stock: 22,
    rating: 4.9,
    reviewCount: 201
  },
  {
    id: 'prod_46',
    slug: 'product-46',
    name: 'Assorted Product 46',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Shoes',
    price: 198906,
    brand: 'Orion',
    images: [{ url: findImage('prod_img_46').url, hint: findImage('prod_img_46').hint }],
    stock: 13,
    rating: 4.6,
    reviewCount: 169
  },
  {
    id: 'prod_47',
    slug: 'product-47',
    name: 'Assorted Product 47',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Watches',
    price: 24716,
    brand: 'Helios',
    images: [{ url: findImage('prod_img_47').url, hint: findImage('prod_img_47').hint }],
    stock: 153,
    rating: 4.4,
    reviewCount: 225
  },
  {
    id: 'prod_48',
    slug: 'product-48',
    name: 'Assorted Product 48',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Underwear',
    price: 147571,
    brand: 'iDino',
    images: [{ url: findImage('prod_img_48').url, hint: findImage('prod_img_48').hint }],
    stock: 174,
    rating: 4.1,
    reviewCount: 310
  },
  {
    id: 'prod_49',
    slug: 'product-49',
    name: 'Assorted Product 49',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Clothes',
    price: 52914,
    brand: 'Aperture',
    images: [{ url: findImage('prod_img_49').url, hint: findImage('prod_img_49').hint }],
    stock: 135,
    rating: 4.4,
    reviewCount: 254
  },
  {
    id: 'prod_50',
    slug: 'product-50',
    name: 'Assorted Product 50',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Wigs',
    price: 76008,
    brand: 'Zenco',
    images: [{ url: findImage('prod_img_50').url, hint: findImage('prod_img_50').hint }],
    stock: 104,
    rating: 4.8,
    reviewCount: 414
  },
  {
    id: 'prod_51',
    slug: 'product-51',
    name: 'Assorted Product 51',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Laptops',
    price: 132474,
    brand: 'Stellar',
    images: [{ url: findImage('prod_img_51').url, hint: findImage('prod_img_51').hint }],
    stock: 182,
    rating: 4.6,
    reviewCount: 279
  },
  {
    id: 'prod_52',
    slug: 'product-52',
    name: 'Assorted Product 52',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Shoes',
    price: 90299,
    brand: 'Nexa',
    images: [{ url: findImage('prod_img_52').url, hint: findImage('prod_img_52').hint }],
    stock: 138,
    rating: 4.9,
    reviewCount: 161
  },
  {
    id: 'prod_53',
    slug: 'product-53',
    name: 'Assorted Product 53',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Watches',
    price: 122822,
    brand: 'Orion',
    images: [{ url: findImage('prod_img_53').url, hint: findImage('prod_img_53').hint }],
    stock: 111,
    rating: 4.0,
    reviewCount: 196
  },
  {
    id: 'prod_54',
    slug: 'product-54',
    name: 'Assorted Product 54',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Underwear',
    price: 169046,
    brand: 'Helios',
    images: [{ url: findImage('prod_img_54').url, hint: findImage('prod_img_54').hint }],
    stock: 195,
    rating: 4.7,
    reviewCount: 288
  },
  {
    id: 'prod_55',
    slug: 'product-55',
    name: 'Assorted Product 55',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Clothes',
    price: 64964,
    brand: 'iDino',
    images: [{ url: findImage('prod_img_55').url, hint: findImage('prod_img_55').hint }],
    stock: 163,
    rating: 4.5,
    reviewCount: 462
  },
  {
    id: 'prod_56',
    slug: 'product-56',
    name: 'Assorted Product 56',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Wigs',
    price: 135894,
    brand: 'Aperture',
    images: [{ url: findImage('prod_img_56').url, hint: findImage('prod_img_56').hint }],
    stock: 13,
    rating: 4.4,
    reviewCount: 300
  },
  {
    id: 'prod_57',
    slug: 'product-57',
    name: 'Assorted Product 57',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Laptops',
    price: 104764,
    brand: 'Zenco',
    images: [{ url: findImage('prod_img_57').url, hint: findImage('prod_img_57').hint }],
    stock: 197,
    rating: 4.0,
    reviewCount: 343
  },
  {
    id: 'prod_58',
    slug: 'product-58',
    name: 'Assorted Product 58',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Shoes',
    price: 11462,
    brand: 'Stellar',
    images: [{ url: findImage('prod_img_58').url, hint: findImage('prod_img_58').hint }],
    stock: 104,
    rating: 4.1,
    reviewCount: 219
  },
  {
    id: 'prod_59',
    slug: 'product-59',
    name: 'Assorted Product 59',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Watches',
    price: 151523,
    brand: 'Nexa',
    images: [{ url: findImage('prod_img_59').url, hint: findImage('prod_img_59').hint }],
    stock: 31,
    rating: 4.9,
    reviewCount: 494
  },
  {
    id: 'prod_60',
    slug: 'product-60',
    name: 'Assorted Product 60',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Underwear',
    price: 122245,
    brand: 'Orion',
    images: [{ url: findImage('prod_img_60').url, hint: findImage('prod_img_60').hint }],
    stock: 87,
    rating: 4.9,
    reviewCount: 161
  },
  {
    id: 'prod_61',
    slug: 'product-61',
    name: 'Assorted Product 61',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Clothes',
    price: 198908,
    brand: 'Helios',
    images: [{ url: findImage('prod_img_61').url, hint: findImage('prod_img_61').hint }],
    stock: 147,
    rating: 4.0,
    reviewCount: 147
  },
  {
    id: 'prod_62',
    slug: 'product-62',
    name: 'Assorted Product 62',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Wigs',
    price: 77529,
    brand: 'iDino',
    images: [{ url: findImage('prod_img_62').url, hint: findImage('prod_img_62').hint }],
    stock: 75,
    rating: 4.8,
    reviewCount: 304
  },
  {
    id: 'prod_63',
    slug: 'product-63',
    name: 'Assorted Product 63',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Laptops',
    price: 184518,
    brand: 'Aperture',
    images: [{ url: findImage('prod_img_63').url, hint: findImage('prod_img_63').hint }],
    stock: 85,
    rating: 4.8,
    reviewCount: 159
  },
  {
    id: 'prod_64',
    slug: 'product-64',
    name: 'Assorted Product 64',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Shoes',
    price: 146193,
    brand: 'Zenco',
    images: [{ url: findImage('prod_img_64').url, hint: findImage('prod_img_64').hint }],
    stock: 106,
    rating: 4.0,
    reviewCount: 462
  },
  {
    id: 'prod_65',
    slug: 'product-65',
    name: 'Assorted Product 65',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Watches',
    price: 190130,
    brand: 'Stellar',
    images: [{ url: findImage('prod_img_65').url, hint: findImage('prod_img_65').hint }],
    stock: 182,
    rating: 4.5,
    reviewCount: 348
  },
  {
    id: 'prod_66',
    slug: 'product-66',
    name: 'Assorted Product 66',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Underwear',
    price: 139947,
    brand: 'Nexa',
    images: [{ url: findImage('prod_img_66').url, hint: findImage('prod_img_66').hint }],
    stock: 125,
    rating: 4.2,
    reviewCount: 172
  },
  {
    id: 'prod_67',
    slug: 'product-67',
    name: 'Assorted Product 67',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Clothes',
    price: 148154,
    brand: 'Orion',
    images: [{ url: findImage('prod_img_67').url, hint: findImage('prod_img_67').hint }],
    stock: 83,
    rating: 4.1,
    reviewCount: 179
  },
  {
    id: 'prod_68',
    slug: 'product-68',
    name: 'Assorted Product 68',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Wigs',
    price: 111162,
    brand: 'Helios',
    images: [{ url: findImage('prod_img_68').url, hint: findImage('prod_img_68').hint }],
    stock: 181,
    rating: 4.4,
    reviewCount: 104
  },
  {
    id: 'prod_69',
    slug: 'product-69',
    name: 'Assorted Product 69',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Laptops',
    price: 169875,
    brand: 'iDino',
    images: [{ url: findImage('prod_img_69').url, hint: findImage('prod_img_69').hint }],
    stock: 163,
    rating: 4.6,
    reviewCount: 114
  },
  {
    id: 'prod_70',
    slug: 'product-70',
    name: 'Assorted Product 70',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Shoes',
    price: 170942,
    brand: 'Aperture',
    images: [{ url: findImage('prod_img_70').url, hint: findImage('prod_img_70').hint }],
    stock: 92,
    rating: 4.2,
    reviewCount: 400
  },
  {
    id: 'prod_71',
    slug: 'product-71',
    name: 'Assorted Product 71',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Watches',
    price: 191636,
    brand: 'Zenco',
    images: [{ url: findImage('prod_img_71').url, hint: findImage('prod_img_71').hint }],
    stock: 164,
    rating: 4.8,
    reviewCount: 220
  },
  {
    id: 'prod_72',
    slug: 'product-72',
    name: 'Assorted Product 72',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Underwear',
    price: 59883,
    brand: 'Stellar',
    images: [{ url: findImage('prod_img_72').url, hint: findImage('prod_img_72').hint }],
    stock: 74,
    rating: 4.6,
    reviewCount: 421
  },
  {
    id: 'prod_73',
    slug: 'product-73',
    name: 'Assorted Product 73',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Clothes',
    price: 136279,
    brand: 'Nexa',
    images: [{ url: findImage('prod_img_73').url, hint: findImage('prod_img_73').hint }],
    stock: 122,
    rating: 4.7,
    reviewCount: 203
  },
  {
    id: 'prod_74',
    slug: 'product-74',
    name: 'Assorted Product 74',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Wigs',
    price: 36767,
    brand: 'Orion',
    images: [{ url: findImage('prod_img_74').url, hint: findImage('prod_img_74').hint }],
    stock: 22,
    rating: 4.5,
    reviewCount: 427
  },
  {
    id: 'prod_75',
    slug: 'product-75',
    name: 'Assorted Product 75',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Laptops',
    price: 52912,
    brand: 'Helios',
    images: [{ url: findImage('prod_img_75').url, hint: findImage('prod_img_75').hint }],
    stock: 181,
    rating: 4.9,
    reviewCount: 167
  },
  {
    id: 'prod_76',
    slug: 'product-76',
    name: 'Assorted Product 76',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Shoes',
    price: 134106,
    brand: 'iDino',
    images: [{ url: findImage('prod_img_76').url, hint: findImage('prod_img_76').hint }],
    stock: 58,
    rating: 4.6,
    reviewCount: 128
  },
  {
    id: 'prod_77',
    slug: 'product-77',
    name: 'Assorted Product 77',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Watches',
    price: 38780,
    brand: 'Aperture',
    images: [{ url: findImage('prod_img_77').url, hint: findImage('prod_img_77').hint }],
    stock: 111,
    rating: 4.7,
    reviewCount: 462
  },
  {
    id: 'prod_78',
    slug: 'product-78',
    name: 'Assorted Product 78',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Underwear',
    price: 15306,
    brand: 'Zenco',
    images: [{ url: findImage('prod_img_78').url, hint: findImage('prod_img_78').hint }],
    stock: 147,
    rating: 4.3,
    reviewCount: 420
  },
  {
    id: 'prod_79',
    slug: 'product-79',
    name: 'Assorted Product 79',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Clothes',
    price: 178734,
    brand: 'Stellar',
    images: [{ url: findImage('prod_img_79').url, hint: findImage('prod_img_79').hint }],
    stock: 198,
    rating: 4.1,
    reviewCount: 461
  },
  {
    id: 'prod_80',
    slug: 'product-80',
    name: 'Assorted Product 80',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Wigs',
    price: 88711,
    brand: 'Nexa',
    images: [{ url: findImage('prod_img_80').url, hint: findImage('prod_img_80').hint }],
    stock: 184,
    rating: 4.2,
    reviewCount: 221
  },
  {
    id: 'prod_81',
    slug: 'product-81',
    name: 'Assorted Product 81',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Laptops',
    price: 66967,
    brand: 'Orion',
    images: [{ url: findImage('prod_img_81').url, hint: findImage('prod_img_81').hint }],
    stock: 45,
    rating: 4.5,
    reviewCount: 395
  },
  {
    id: 'prod_82',
    slug: 'product-82',
    name: 'Assorted Product 82',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Shoes',
    price: 24765,
    brand: 'Helios',
    images: [{ url: findImage('prod_img_82').url, hint: findImage('prod_img_82').hint }],
    stock: 149,
    rating: 4.7,
    reviewCount: 351
  },
  {
    id: 'prod_83',
    slug: 'product-83',
    name: 'Assorted Product 83',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Watches',
    price: 78566,
    brand: 'iDino',
    images: [{ url: findImage('prod_img_83').url, hint: findImage('prod_img_83').hint }],
    stock: 153,
    rating: 4.2,
    reviewCount: 368
  },
  {
    id: 'prod_84',
    slug: 'product-84',
    name: 'Assorted Product 84',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Underwear',
    price: 60920,
    brand: 'Aperture',
    images: [{ url: findImage('prod_img_84').url, hint: findImage('prod_img_84').hint }],
    stock: 110,
    rating: 4.9,
    reviewCount: 228
  },
  {
    id: 'prod_85',
    slug: 'product-85',
    name: 'Assorted Product 85',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Clothes',
    price: 153361,
    brand: 'Zenco',
    images: [{ url: findImage('prod_img_85').url, hint: findImage('prod_img_85').hint }],
    stock: 13,
    rating: 4.8,
    reviewCount: 468
  },
  {
    id: 'prod_86',
    slug: 'product-86',
    name: 'Assorted Product 86',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Wigs',
    price: 185672,
    brand: 'Stellar',
    images: [{ url: findImage('prod_img_86').url, hint: findImage('prod_img_86').hint }],
    stock: 116,
    rating: 4.3,
    reviewCount: 421
  },
  {
    id: 'prod_87',
    slug: 'product-87',
    name: 'Assorted Product 87',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Laptops',
    price: 78598,
    brand: 'Nexa',
    images: [{ url: findImage('prod_img_87').url, hint: findImage('prod_img_87').hint }],
    stock: 94,
    rating: 4.6,
    reviewCount: 351
  },
  {
    id: 'prod_88',
    slug: 'product-88',
    name: 'Assorted Product 88',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Shoes',
    price: 157317,
    brand: 'Orion',
    images: [{ url: findImage('prod_img_88').url, hint: findImage('prod_img_88').hint }],
    stock: 135,
    rating: 4.4,
    reviewCount: 457
  },
  {
    id: 'prod_89',
    slug: 'product-89',
    name: 'Assorted Product 89',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Watches',
    price: 104523,
    brand: 'Helios',
    images: [{ url: findImage('prod_img_89').url, hint: findImage('prod_img_89').hint }],
    stock: 154,
    rating: 4.5,
    reviewCount: 409
  },
  {
    id: 'prod_90',
    slug: 'product-90',
    name: 'Assorted Product 90',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Underwear',
    price: 180214,
    brand: 'iDino',
    images: [{ url: findImage('prod_img_90').url, hint: findImage('prod_img_90').hint }],
    stock: 75,
    rating: 4.7,
    reviewCount: 310
  },
  {
    id: 'prod_91',
    slug: 'product-91',
    name: 'Assorted Product 91',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Clothes',
    price: 84646,
    brand: 'Aperture',
    images: [{ url: findImage('prod_img_91').url, hint: findImage('prod_img_91').hint }],
    stock: 22,
    rating: 4.3,
    reviewCount: 229
  },
  {
    id: 'prod_92',
    slug: 'product-92',
    name: 'Assorted Product 92',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Wigs',
    price: 191845,
    brand: 'Zenco',
    images: [{ url: findImage('prod_img_92').url, hint: findImage('prod_img_92').hint }],
    stock: 122,
    rating: 4.9,
    reviewCount: 161
  },
  {
    id: 'prod_93',
    slug: 'product-93',
    name: 'Assorted Product 93',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Laptops',
    price: 24718,
    brand: 'Stellar',
    images: [{ url: findImage('prod_img_93').url, hint: findImage('prod_img_93').hint }],
    stock: 147,
    rating: 4.0,
    reviewCount: 295
  },
  {
    id: 'prod_94',
    slug: 'product-94',
    name: 'Assorted Product 94',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Shoes',
    price: 123984,
    brand: 'Nexa',
    images: [{ url: findImage('prod_img_94').url, hint: findImage('prod_img_94').hint }],
    stock: 187,
    rating: 4.3,
    reviewCount: 301
  },
  {
    id: 'prod_95',
    slug: 'product-95',
    name: 'Assorted Product 95',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Watches',
    price: 89632,
    brand: 'Orion',
    images: [{ url: findImage('prod_img_95').url, hint: findImage('prod_img_95').hint }],
    stock: 75,
    rating: 4.5,
    reviewCount: 341
  },
  {
    id: 'prod_96',
    slug: 'product-96',
    name: 'Assorted Product 96',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Underwear',
    price: 90977,
    brand: 'Helios',
    images: [{ url: findImage('prod_img_96').url, hint: findImage('prod_img_96').hint }],
    stock: 31,
    rating: 4.6,
    reviewCount: 185
  },
  {
    id: 'prod_97',
    slug: 'product-97',
    name: 'Assorted Product 97',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Clothes',
    price: 16183,
    brand: 'iDino',
    images: [{ url: findImage('prod_img_97').url, hint: findImage('prod_img_97').hint }],
    stock: 167,
    rating: 4.4,
    reviewCount: 421
  },
  {
    id: 'prod_98',
    slug: 'product-98',
    name: 'Assorted Product 98',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Wigs',
    price: 110996,
    brand: 'Aperture',
    images: [{ url: findImage('prod_img_98').url, hint: findImage('prod_img_98').hint }],
    stock: 63,
    rating: 4.2,
    reviewCount: 182
  },
  {
    id: 'prod_99',
    slug: 'product-99',
    name: 'Assorted Product 99',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Laptops',
    price: 66965,
    brand: 'Zenco',
    images: [{ url: findImage('prod_img_99').url, hint: findImage('prod_img_99').hint }],
    stock: 79,
    rating: 4.2,
    reviewCount: 227
  },
  {
    id: 'prod_100',
    slug: 'product-100',
    name: 'Assorted Product 100',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Shoes',
    price: 125199,
    brand: 'Stellar',
    images: [{ url: findImage('prod_img_100').url, hint: findImage('prod_img_100').hint }],
    stock: 187,
    rating: 4.9,
    reviewCount: 279
  },
  {
    id: 'prod_101',
    slug: 'product-101',
    name: 'Assorted Product 101',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Watches',
    price: 198944,
    brand: 'Nexa',
    images: [{ url: findImage('prod_img_101').url, hint: findImage('prod_img_101').hint }],
    stock: 94,
    rating: 4.2,
    reviewCount: 104
  },
  {
    id: 'prod_102',
    slug: 'product-102',
    name: 'Assorted Product 102',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Underwear',
    price: 111306,
    brand: 'Orion',
    images: [{ url: findImage('prod_img_102').url, hint: findImage('prod_img_102').hint }],
    stock: 45,
    rating: 4.4,
    reviewCount: 379
  },
  {
    id: 'prod_103',
    slug: 'product-103',
    name: 'Assorted Product 103',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Clothes',
    price: 88514,
    brand: 'Helios',
    images: [{ url: findImage('prod_img_103').url, hint: findImage('prod_img_103').hint }],
    stock: 121,
    rating: 4.8,
    reviewCount: 307
  },
  {
    id: 'prod_104',
    slug: 'product-104',
    name: 'Assorted Product 104',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Wigs',
    price: 147610,
    brand: 'iDino',
    images: [{ url: findImage('prod_img_104').url, hint: findImage('prod_img_104').hint }],
    stock: 104,
    rating: 4.9,
    reviewCount: 367
  },
  {
    id: 'prod_105',
    slug: 'product-105',
    name: 'Assorted Product 105',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Laptops',
    price: 15998,
    brand: 'Aperture',
    images: [{ url: findImage('prod_img_105').url, hint: findImage('prod_img_105').hint }],
    stock: 182,
    rating: 4.0,
    reviewCount: 326
  },
  {
    id: 'prod_106',
    slug: 'product-106',
    name: 'Assorted Product 106',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Shoes',
    price: 36173,
    brand: 'Zenco',
    images: [{ url: findImage('prod_img_106').url, hint: findImage('prod_img_106').hint }],
    stock: 16,
    rating: 4.4,
    reviewCount: 388
  },
  {
    id: 'prod_107',
    slug: 'product-107',
    name: 'Assorted Product 107',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Watches',
    price: 84310,
    brand: 'Stellar',
    images: [{ url: findImage('prod_img_107').url, hint: findImage('prod_img_107').hint }],
    stock: 122,
    rating: 4.9,
    reviewCount: 227
  },
  {
    id: 'prod_108',
    slug: 'product-108',
    name: 'Assorted Product 108',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Underwear',
    price: 13575,
    brand: 'Nexa',
    images: [{ url: findImage('prod_img_108').url, hint: findImage('prod_img_108').hint }],
    stock: 198,
    rating: 4.7,
    reviewCount: 201
  },
  {
    id: 'prod_109',
    slug: 'product-109',
    name: 'Assorted Product 109',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Clothes',
    price: 17294,
    brand: 'Orion',
    images: [{ url: findImage('prod_img_109').url, hint: findImage('prod_img_109').hint }],
    stock: 176,
    rating: 4.8,
    reviewCount: 381
  },
  {
    id: 'prod_110',
    slug: 'product-110',
    name: 'Assorted Product 110',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Wigs',
    price: 121511,
    brand: 'Helios',
    images: [{ url: findImage('prod_img_110').url, hint: findImage('prod_img_110').hint }],
    stock: 12,
    rating: 4.1,
    reviewCount: 450
  },
  {
    id: 'prod_111',
    slug: 'product-111',
    name: 'Assorted Product 111',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Laptops',
    price: 193231,
    brand: 'iDino',
    images: [{ url: findImage('prod_img_111').url, hint: findImage('prod_img_111').hint }],
    stock: 144,
    rating: 4.4,
    reviewCount: 169
  },
  {
    id: 'prod_112',
    slug: 'product-112',
    name: 'Assorted Product 112',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Shoes',
    price: 133276,
    brand: 'Aperture',
    images: [{ url: findImage('prod_img_112').url, hint: findImage('prod_img_112').hint }],
    stock: 39,
    rating: 4.3,
    reviewCount: 308
  },
  {
    id: 'prod_113',
    slug: 'product-113',
    name: 'Assorted Product 113',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Watches',
    price: 13083,
    brand: 'Zenco',
    images: [{ url: findImage('prod_img_113').url, hint: findImage('prod_img_113').hint }],
    stock: 143,
    rating: 4.9,
    reviewCount: 228
  },
  {
    id: 'prod_114',
    slug: 'product-114',
    name: 'Assorted Product 114',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Underwear',
    price: 194098,
    brand: 'Stellar',
    images: [{ url: findImage('prod_img_114').url, hint: findImage('prod_img_114').hint }],
    stock: 33,
    rating: 4.2,
    reviewCount: 236
  },
  {
    id: 'prod_115',
    slug: 'product-115',
    name: 'Assorted Product 115',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Clothes',
    price: 176166,
    brand: 'Nexa',
    images: [{ url: findImage('prod_img_115').url, hint: findImage('prod_img_115').hint }],
    stock: 124,
    rating: 4.9,
    reviewCount: 167
  },
  {
    id: 'prod_116',
    slug: 'product-116',
    name: 'Assorted Product 116',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Wigs',
    price: 59715,
    brand: 'Orion',
    images: [{ url: findImage('prod_img_116').url, hint: findImage('prod_img_116').hint }],
    stock: 171,
    rating: 4.8,
    reviewCount: 421
  },
  {
    id: 'prod_117',
    slug: 'product-117',
    name: 'Assorted Product 117',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Laptops',
    price: 29555,
    brand: 'Helios',
    images: [{ url: findImage('prod_img_117').url, hint: findImage('prod_img_117').hint }],
    stock: 75,
    rating: 4.6,
    reviewCount: 165
  },
  {
    id: 'prod_118',
    slug: 'product-118',
    name: 'Assorted Product 118',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Shoes',
    price: 174697,
    brand: 'iDino',
    images: [{ url: findImage('prod_img_118').url, hint: findImage('prod_img_118').hint }],
    stock: 24,
    rating: 4.8,
    reviewCount: 312
  },
  {
    id: 'prod_119',
    slug: 'product-119',
    name: 'Assorted Product 119',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Watches',
    price: 115201,
    brand: 'Aperture',
    images: [{ url: findImage('prod_img_119').url, hint: findImage('prod_img_119').hint }],
    stock: 115,
    rating: 4.6,
    reviewCount: 228
  },
  {
    id: 'prod_120',
    slug: 'product-120',
    name: 'Assorted Product 120',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Underwear',
    price: 36720,
    brand: 'Zenco',
    images: [{ url: findImage('prod_img_120').url, hint: findImage('prod_img_120').hint }],
    stock: 139,
    rating: 4.2,
    reviewCount: 381
  },
  {
    id: 'prod_121',
    slug: 'product-121',
    name: 'Assorted Product 121',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Clothes',
    price: 52026,
    brand: 'Stellar',
    images: [{ url: findImage('prod_img_121').url, hint: findImage('prod_img_121').hint }],
    stock: 99,
    rating: 4.3,
    reviewCount: 201
  },
  {
    id: 'prod_122',
    slug: 'product-122',
    name: 'Assorted Product 122',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Wigs',
    price: 171424,
    brand: 'Nexa',
    images: [{ url: findImage('prod_img_122').url, hint: findImage('prod_img_122').hint }],
    stock: 24,
    rating: 4.9,
    reviewCount: 202
  },
  {
    id: 'prod_123',
    slug: 'product-123',
    name: 'Assorted Product 123',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Laptops',
    price: 141235,
    brand: 'Orion',
    images: [{ url: findImage('prod_img_123').url, hint: findImage('prod_img_123').hint }],
    stock: 13,
    rating: 4.0,
    reviewCount: 414
  },
  {
    id: 'prod_124',
    slug: 'product-124',
    name: 'Assorted Product 124',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Shoes',
    price: 110036,
    brand: 'Helios',
    images: [{ url: findImage('prod_img_124').url, hint: findImage('prod_img_124').hint }],
    stock: 58,
    rating: 4.8,
    reviewCount: 304
  },
  {
    id: 'prod_125',
    slug: 'product-125',
    name: 'Assorted Product 125',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Watches',
    price: 181315,
    brand: 'iDino',
    images: [{ url: findImage('prod_img_125').url, hint: findImage('prod_img_125').hint }],
    stock: 153,
    rating: 4.7,
    reviewCount: 226
  },
  {
    id: 'prod_126',
    slug: 'product-126',
    name: 'Assorted Product 126',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Underwear',
    price: 113970,
    brand: 'Aperture',
    images: [{ url: findImage('prod_img_126').url, hint: findImage('prod_img_126').hint }],
    stock: 120,
    rating: 4.8,
    reviewCount: 250
  },
  {
    id: 'prod_127',
    slug: 'product-127',
    name: 'Assorted Product 127',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Clothes',
    price: 121307,
    brand: 'Zenco',
    images: [{ url: findImage('prod_img_127').url, hint: findImage('prod_img_127').hint }],
    stock: 161,
    rating: 4.7,
    reviewCount: 479
  },
  {
    id: 'prod_128',
    slug: 'product-128',
    name: 'Assorted Product 128',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Wigs',
    price: 133827,
    brand: 'Stellar',
    images: [{ url: findImage('prod_img_128').url, hint: findImage('prod_img_128').hint }],
    stock: 82,
    rating: 4.4,
    reviewCount: 395
  },
  {
    id: 'prod_129',
    slug: 'product-129',
    name: 'Assorted Product 129',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Laptops',
    price: 17095,
    brand: 'Nexa',
    images: [{ url: findImage('prod_img_129').url, hint: findImage('prod_img_129').hint }],
    stock: 75,
    rating: 4.7,
    reviewCount: 227
  },
  {
    id: 'prod_130',
    slug: 'product-130',
    name: 'Assorted Product 130',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Shoes',
    price: 106395,
    brand: 'Orion',
    images: [{ url: findImage('prod_img_130').url, hint: findImage('prod_img_130').hint }],
    stock: 122,
    rating: 4.8,
    reviewCount: 461
  },
  {
    id: 'prod_131',
    slug: 'product-131',
    name: 'Assorted Product 131',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Watches',
    price: 66928,
    brand: 'Helios',
    images: [{ url: findImage('prod_img_131').url, hint: findImage('prod_img_131').hint }],
    stock: 87,
    rating: 4.0,
    reviewCount: 167
  },
  {
    id: 'prod_132',
    slug: 'product-132',
    name: 'Assorted Product 132',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Underwear',
    price: 81969,
    brand: 'iDino',
    images: [{ url: findImage('prod_img_132').url, hint: findImage('prod_img_132').hint }],
    stock: 166,
    rating: 4.5,
    reviewCount: 133
  },
  {
    id: 'prod_133',
    slug: 'product-133',
    name: 'Assorted Product 133',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Clothes',
    price: 147814,
    brand: 'Aperture',
    images: [{ url: findImage('prod_img_133').url, hint: findImage('prod_img_133').hint }],
    stock: 187,
    rating: 4.0,
    reviewCount: 201
  },
  {
    id: 'prod_134',
    slug: 'product-134',
    name: 'Assorted Product 134',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Wigs',
    price: 160086,
    brand: 'Zenco',
    images: [{ url: findImage('prod_img_134').url, hint: findImage('prod_img_134').hint }],
    stock: 58,
    rating: 4.2,
    reviewCount: 182
  },
  {
    id: 'prod_135',
    slug: 'product-135',
    name: 'Assorted Product 135',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Laptops',
    price: 137882,
    brand: 'Stellar',
    images: [{ url: findImage('prod_img_135').url, hint: findImage('prod_img_135').hint }],
    stock: 141,
    rating: 4.4,
    reviewCount: 186
  },
  {
    id: 'prod_136',
    slug: 'product-136',
    name: 'Assorted Product 136',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Shoes',
    price: 26034,
    brand: 'Nexa',
    images: [{ url: findImage('prod_img_136').url, hint: findImage('prod_img_136').hint }],
    stock: 99,
    rating: 4.8,
    reviewCount: 171
  },
  {
    id: 'prod_137',
    slug: 'product-137',
    name: 'Assorted Product 137',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Watches',
    price: 151591,
    brand: 'Orion',
    images: [{ url: findImage('prod_img_137').url, hint: findImage('prod_img_137').hint }],
    stock: 31,
    rating: 4.9,
    reviewCount: 301
  },
  {
    id: 'prod_138',
    slug: 'product-138',
    name: 'Assorted Product 138',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Underwear',
    price: 130328,
    brand: 'Helios',
    images: [{ url: findImage('prod_img_138').url, hint: findImage('prod_img_138').hint }],
    stock: 104,
    rating: 4.4,
    reviewCount: 122
  },
  {
    id: 'prod_139',
    slug: 'product-139',
    name: 'Assorted Product 139',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Clothes',
    price: 196887,
    brand: 'iDino',
    images: [{ url: findImage('prod_img_139').url, hint: findImage('prod_img_139').hint }],
    stock: 147,
    rating: 4.8,
    reviewCount: 221
  },
  {
    id: 'prod_140',
    slug: 'product-140',
    name: 'Assorted Product 140',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Wigs',
    price: 144574,
    brand: 'Aperture',
    images: [{ url: findImage('prod_img_140').url, hint: findImage('prod_img_140').hint }],
    stock: 171,
    rating: 4.3,
    reviewCount: 388
  },
  {
    id: 'prod_141',
    slug: 'product-141',
    name: 'Assorted Product 141',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Laptops',
    price: 168676,
    brand: 'Zenco',
    images: [{ url: findImage('prod_img_141').url, hint: findImage('prod_img_141').hint }],
    stock: 114,
    rating: 4.9,
    reviewCount: 462
  },
  {
    id: 'prod_142',
    slug: 'product-142',
    name: 'Assorted Product 142',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Shoes',
    price: 179507,
    brand: 'Stellar',
    images: [{ url: findImage('prod_img_142').url, hint: findImage('prod_img_142').hint }],
    stock: 14,
    rating: 4.7,
    reviewCount: 228
  },
  {
    id: 'prod_143',
    slug: 'product-143',
    name: 'Assorted Product 143',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Watches',
    price: 88788,
    brand: 'Nexa',
    images: [{ url: findImage('prod_img_143').url, hint: findImage('prod_img_143').hint }],
    stock: 33,
    rating: 4.1,
    reviewCount: 395
  },
  {
    id: 'prod_144',
    slug: 'product-144',
    name: 'Assorted Product 144',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Underwear',
    price: 191632,
    brand: 'Orion',
    images: [{ url: findImage('prod_img_144').url, hint: findImage('prod_img_144').hint }],
    stock: 104,
    rating: 4.7,
    reviewCount: 161
  },
  {
    id: 'prod_145',
    slug: 'product-145',
    name: 'Assorted Product 145',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Clothes',
    price: 90280,
    brand: 'Helios',
    images: [{ url: findImage('prod_img_145').url, hint: findImage('prod_img_145').hint }],
    stock: 58,
    rating: 4.0,
    reviewCount: 221
  },
  {
    id: 'prod_146',
    slug: 'product-146',
    name: 'Assorted Product 146',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Wigs',
    price: 114624,
    brand: 'iDino',
    images: [{ url: findImage('prod_img_146').url, hint: findImage('prod_img_146').hint }],
    stock: 147,
    rating: 4.3,
    reviewCount: 181
  },
  {
    id: 'prod_147',
    slug: 'product-147',
    name: 'Assorted Product 147',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Laptops',
    price: 167512,
    brand: 'Aperture',
    images: [{ url: findImage('prod_img_147').url, hint: findImage('prod_img_147').hint }],
    stock: 161,
    rating: 4.2,
    reviewCount: 128
  },
  {
    id: 'prod_148',
    slug: 'product-148',
    name: 'Assorted Product 148',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Shoes',
    price: 140026,
    brand: 'Zenco',
    images: [{ url: findImage('prod_img_148').url, hint: findImage('prod_img_148').hint }],
    stock: 144,
    rating: 4.1,
    reviewCount: 228
  },
  {
    id: 'prod_149',
    slug: 'product-149',
    name: 'Assorted Product 149',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Watches',
    price: 76092,
    brand: 'Stellar',
    images: [{ url: findImage('prod_img_149').url, hint: findImage('prod_img_149').hint }],
    stock: 166,
    rating: 4.2,
    reviewCount: 250
  },
  {
    id: 'prod_150',
    slug: 'product-150',
    name: 'Assorted Product 150',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Underwear',
    price: 110959,
    brand: 'Nexa',
    images: [{ url: findImage('prod_img_150').url, hint: findImage('prod_img_150').hint }],
    stock: 191,
    rating: 4.6,
    reviewCount: 261
  },
  {
    id: 'prod_151',
    slug: 'product-151',
    name: 'Assorted Product 151',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Clothes',
    price: 15306,
    brand: 'Orion',
    images: [{ url: findImage('prod_img_151').url, hint: findImage('prod_img_151').hint }],
    stock: 198,
    rating: 4.5,
    reviewCount: 304
  },
  {
    id: 'prod_152',
    slug: 'product-152',
    name: 'Assorted Product 152',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Wigs',
    price: 36768,
    brand: 'Helios',
    images: [{ url: findImage('prod_img_152').url, hint: findImage('prod_img_152').hint }],
    stock: 167,
    rating: 4.4,
    reviewCount: 360
  },
  {
    id: 'prod_153',
    slug: 'product-153',
    name: 'Assorted Product 153',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Laptops',
    price: 172978,
    brand: 'iDino',
    images: [{ url: findImage('prod_img_153').url, hint: findImage('prod_img_153').hint }],
    stock: 13,
    rating: 4.0,
    reviewCount: 421
  },
  {
    id: 'prod_154',
    slug: 'product-154',
    name: 'Assorted Product 154',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Shoes',
    price: 155823,
    brand: 'Aperture',
    images: [{ url: findImage('prod_img_154').url, hint: findImage('prod_img_154').hint }],
    stock: 104,
    rating: 4.7,
    reviewCount: 167
  },
  {
    id: 'prod_155',
    slug: 'product-155',
    name: 'Assorted Product 155',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Watches',
    price: 120562,
    brand: 'Zenco',
    images: [{ url: findImage('prod_img_155').url, hint: findImage('prod_img_155').hint }],
    stock: 111,
    rating: 4.1,
    reviewCount: 326
  },
  {
    id: 'prod_156',
    slug: 'product-156',
    name: 'Assorted Product 156',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Underwear',
    price: 25176,
    brand: 'Stellar',
    images: [{ url: findImage('prod_img_156').url, hint: findImage('prod_img_156').hint }],
    stock: 94,
    rating: 4.9,
    reviewCount: 367
  },
  {
    id: 'prod_157',
    slug: 'product-157',
    name: 'Assorted Product 157',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Clothes',
    price: 124376,
    brand: 'Nexa',
    images: [{ url: findImage('prod_img_157').url, hint: findImage('prod_img_157').hint }],
    stock: 12,
    rating: 4.9,
    reviewCount: 310
  },
  {
    id: 'prod_158',
    slug: 'product-158',
    name: 'Assorted Product 158',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Wigs',
    price: 54641,
    brand: 'Orion',
    images: [{ url: findImage('prod_img_158').url, hint: findImage('prod_img_158').hint }],
    stock: 139,
    rating: 4.0,
    reviewCount: 228
  },
  {
    id: 'prod_159',
    slug: 'product-159',
    name: 'Assorted Product 159',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Laptops',
    price: 94254,
    brand: 'Helios',
    images: [{ url: findImage('prod_img_159').url, hint: findImage('prod_img_159').hint }],
    stock: 14,
    rating: 4.1,
    reviewCount: 167
  },
  {
    id: 'prod_160',
    slug: 'product-160',
    name: 'Assorted Product 160',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Shoes',
    price: 185121,
    brand: 'iDino',
    images: [{ url: findImage('prod_img_160').url, hint: findImage('prod_img_160').hint }],
    stock: 189,
    rating: 4.0,
    reviewCount: 461
  },
  {
    id: 'prod_161',
    slug: 'product-161',
    name: 'Assorted Product 161',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Watches',
    price: 36768,
    brand: 'Aperture',
    images: [{ url: findImage('prod_img_161').url, hint: findImage('prod_img_161').hint }],
    stock: 147,
    rating: 4.6,
    reviewCount: 232
  },
  {
    id: 'prod_162',
    slug: 'product-162',
    name: 'Assorted Product 162',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Underwear',
    price: 198906,
    brand: 'Zenco',
    images: [{ url: findImage('prod_img_162').url, hint: findImage('prod_img_162').hint }],
    stock: 104,
    rating: 4.6,
    reviewCount: 221
  },
  {
    id: 'prod_163',
    slug: 'product-163',
    name: 'Assorted Product 163',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Clothes',
    price: 147571,
    brand: 'Stellar',
    images: [{ url: findImage('prod_img_163').url, hint: findImage('prod_img_163').hint }],
    stock: 122,
    rating: 4.5,
    reviewCount: 167
  },
  {
    id: 'prod_164',
    slug: 'product-164',
    name: 'Assorted Product 164',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Wigs',
    price: 52914,
    brand: 'Nexa',
    images: [{ url: findImage('prod_img_164').url, hint: findImage('prod_img_164').hint }],
    stock: 149,
    rating: 4.7,
    reviewCount: 462
  },
  {
    id: 'prod_165',
    slug: 'product-165',
    name: 'Assorted Product 165',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Laptops',
    price: 132474,
    brand: 'Orion',
    images: [{ url: findImage('prod_img_165').url, hint: findImage('prod_img_165').hint }],
    stock: 104,
    rating: 4.2,
    reviewCount: 184
  },
  {
    id: 'prod_166',
    slug: 'product-166',
    name: 'Assorted Product 166',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Shoes',
    price: 122822,
    brand: 'Helios',
    images: [{ url: findImage('prod_img_166').url, hint: findImage('prod_img_166').hint }],
    stock: 122,
    rating: 4.0,
    reviewCount: 381
  },
  {
    id: 'prod_167',
    slug: 'product-167',
    name: 'Assorted Product 167',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Watches',
    price: 64964,
    brand: 'iDino',
    images: [{ url: findImage('prod_img_167').url, hint: findImage('prod_img_167').hint }],
    stock: 75,
    rating: 4.9,
    reviewCount: 167
  },
  {
    id: 'prod_168',
    slug: 'product-168',
    name: 'Assorted Product 168',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Underwear',
    price: 11462,
    brand: 'Aperture',
    images: [{ url: findImage('prod_img_168').url, hint: findImage('prod_img_168').hint }],
    stock: 147,
    rating: 4.3,
    reviewCount: 304
  },
  {
    id: 'prod_169',
    slug: 'product-169',
    name: 'Assorted Product 169',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Clothes',
    price: 122245,
    brand: 'Zenco',
    images: [{ url: findImage('prod_img_169').url, hint: findImage('prod_img_169').hint }],
    stock: 135,
    rating: 4.2,
    reviewCount: 159
  },
  {
    id: 'prod_170',
    slug: 'product-170',
    name: 'Assorted Product 170',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Wigs',
    price: 198908,
    brand: 'Stellar',
    images: [{ url: findImage('prod_img_170').url, hint: findImage('prod_img_170').hint }],
    stock: 141,
    rating: 4.8,
    reviewCount: 301
  },
  {
    id: 'prod_171',
    slug: 'product-171',
    name: 'Assorted Product 171',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Laptops',
    price: 77529,
    brand: 'Nexa',
    images: [{ url: findImage('prod_img_171').url, hint: findImage('prod_img_171').hint }],
    stock: 12,
    rating: 4.9,
    reviewCount: 221
  },
  {
    id: 'prod_172',
    slug: 'product-172',
    name: 'Assorted Product 172',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Shoes',
    price: 146193,
    brand: 'Orion',
    images: [{ url: findImage('prod_img_172').url, hint: findImage('prod_img_172').hint }],
    stock: 181,
    rating: 4.0,
    reviewCount: 228
  },
  {
    id: 'prod_173',
    slug: 'product-173',
    name: 'Assorted Product 173',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Watches',
    price: 139947,
    brand: 'Helios',
    images: [{ url: findImage('prod_img_173').url, hint: findImage('prod_img_173').hint }],
    stock: 163,
    rating: 4.0,
    reviewCount: 167
  },
  {
    id: 'prod_174',
    slug: 'product-174',
    name: 'Assorted Product 174',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Underwear',
    price: 111162,
    brand: 'iDino',
    images: [{ url: findImage('prod_img_174').url, hint: findImage('prod_img_174').hint }],
    stock: 147,
    rating: 4.8,
    reviewCount: 308
  },
  {
    id: 'prod_175',
    slug: 'product-175',
    name: 'Assorted Product 175',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Clothes',
    price: 191636,
    brand: 'Aperture',
    images: [{ url: findImage('prod_img_175').url, hint: findImage('prod_img_175').hint }],
    stock: 187,
    rating: 4.9,
    reviewCount: 326
  },
  {
    id: 'prod_176',
    slug: 'product-176',
    name: 'Assorted Product 176',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Wigs',
    price: 136279,
    brand: 'Zenco',
    images: [{ url: findImage('prod_img_176').url, hint: findImage('prod_img_176').hint }],
    stock: 164,
    rating: 4.9,
    reviewCount: 367
  },
  {
    id: 'prod_177',
    slug: 'product-177',
    name: 'Assorted Product 177',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Laptops',
    price: 180214,
    brand: 'Stellar',
    images: [{ url: findImage('prod_img_177').url, hint: findImage('prod_img_177').hint }],
    stock: 174,
    rating: 4.2,
    reviewCount: 182
  },
  {
    id: 'prod_178',
    slug: 'product-178',
    name: 'Assorted Product 178',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Shoes',
    price: 84646,
    brand: 'Nexa',
    images: [{ url: findImage('prod_img_178').url, hint: findImage('prod_img_178').hint }],
    stock: 184,
    rating: 4.3,
    reviewCount: 228
  },
  {
    id: 'prod_179',
    slug: 'product-179',
    name: 'Assorted Product 179',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Watches',
    price: 24718,
    brand: 'Orion',
    images: [{ url: findImage('prod_img_179').url, hint: findImage('prod_img_179').hint }],
    stock: 187,
    rating: 4.8,
    reviewCount: 381
  },
  {
    id: 'prod_180',
    slug: 'product-180',
    name: 'Assorted Product 180',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Underwear',
    price: 89632,
    brand: 'Helios',
    images: [{ url: findImage('prod_img_180').url, hint: findImage('prod_img_180').hint }],
    stock: 94,
    rating: 4.8,
    reviewCount: 461
  },
  {
    id: 'prod_181',
    slug: 'product-181',
    name: 'Assorted Product 181',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Clothes',
    price: 16183,
    brand: 'iDino',
    images: [{ url: findImage('prod_img_181').url, hint: findImage('prod_img_181').hint }],
    stock: 147,
    rating: 4.9,
    reviewCount: 414
  },
  {
    id: 'prod_182',
    slug: 'product-182',
    name: 'Assorted Product 182',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Wigs',
    price: 66965,
    brand: 'Aperture',
    images: [{ url: findImage('prod_img_182').url, hint: findImage('prod_img_182').hint }],
    stock: 122,
    rating: 4.2,
    reviewCount: 395
  },
  {
    id: 'prod_183',
    slug: 'product-183',
    name: 'Assorted Product 183',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Laptops',
    price: 198944,
    brand: 'Zenco',
    images: [{ url: findImage('prod_img_183').url, hint: findImage('prod_img_183').hint }],
    stock: 12,
    rating: 4.7,
    reviewCount: 167
  },
  {
    id: 'prod_184',
    slug: 'product-184',
    name: 'Assorted Product 184',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Shoes',
    price: 88514,
    brand: 'Stellar',
    images: [{ url: findImage('prod_img_184').url, hint: findImage('prod_img_184').hint }],
    stock: 181,
    rating: 4.3,
    reviewCount: 227
  },
  {
    id: 'prod_185',
    slug: 'product-185',
    name: 'Assorted Product 185',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Watches',
    price: 15998,
    brand: 'Nexa',
    images: [{ url: findImage('prod_img_185').url, hint: findImage('prod_img_185').hint }],
    stock: 187,
    rating: 4.1,
    reviewCount: 201
  },
  {
    id: 'prod_186',
    slug: 'product-186',
    name: 'Assorted Product 186',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Underwear',
    price: 84310,
    brand: 'Orion',
    images: [{ url: findImage('prod_img_186').url, hint: findImage('prod_img_186').hint }],
    stock: 99,
    rating: 4.5,
    reviewCount: 462
  },
  {
    id: 'prod_187',
    slug: 'product-187',
    name: 'Assorted Product 187',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Clothes',
    price: 17294,
    brand: 'Helios',
    images: [{ url: findImage('prod_img_187').url, hint: findImage('prod_img_187').hint }],
    stock: 147,
    rating: 4.0,
    reviewCount: 161
  },
  {
    id: 'prod_188',
    slug: 'product-188',
    name: 'Assorted Product 188',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Wigs',
    price: 193231,
    brand: 'iDino',
    images: [{ url: findImage('prod_img_188').url, hint: findImage('prod_img_188').hint }],
    stock: 13,
    rating: 4.6,
    reviewCount: 181
  },
  {
    id: 'prod_189',
    slug: 'product-189',
    name: 'Assorted Product 189',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Laptops',
    price: 13083,
    brand: 'Aperture',
    images: [{ url: findImage('prod_img_189').url, hint: findImage('prod_img_189').hint }],
    stock: 124,
    rating: 4.7,
    reviewCount: 301
  },
  {
    id: 'prod_190',
    slug: 'product-190',
    name: 'Assorted Product 190',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Shoes',
    price: 176166,
    brand: 'Zenco',
    images: [{ url: findImage('prod_img_190').url, hint: findImage('prod_img_190').hint }],
    stock: 75,
    rating: 4.0,
    reviewCount: 360
  },
  {
    id: 'prod_191',
    slug: 'product-191',
    name: 'Assorted Product 191',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Watches',
    price: 29555,
    brand: 'Stellar',
    images: [{ url: findImage('prod_img_191').url, hint: findImage('prod_img_191').hint }],
    stock: 147,
    rating: 4.7,
    reviewCount: 167
  },
  {
    id: 'prod_192',
    slug: 'product-192',
    name: 'Assorted Product 192',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Underwear',
    price: 115201,
    brand: 'Nexa',
    images: [{ url: findImage('prod_img_192').url, hint: findImage('prod_img_192').hint }],
    stock: 139,
    rating: 4.8,
    reviewCount: 421
  },
  {
    id: 'prod_193',
    slug: 'product-193',
    name: 'Assorted Product 193',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Clothes',
    price: 36720,
    brand: 'Orion',
    images: [{ url: findImage('prod_img_193').url, hint: findImage('prod_img_193').hint }],
    stock: 12,
    rating: 4.8,
    reviewCount: 308
  },
  {
    id: 'prod_194',
    slug: 'product-194',
    name: 'Assorted Product 194',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Wigs',
    price: 171424,
    brand: 'Helios',
    images: [{ url: findImage('prod_img_194').url, hint: findImage('prod_img_194').hint }],
    stock: 141,
    rating: 4.0,
    reviewCount: 228
  },
  {
    id: 'prod_195',
    slug: 'product-195',
    name: 'Assorted Product 195',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Laptops',
    price: 110036,
    brand: 'iDino',
    images: [{ url: findImage('prod_img_195').url, hint: findImage('prod_img_195').hint }],
    stock: 153,
    rating: 4.4,
    reviewCount: 236
  },
  {
    id: 'prod_196',
    slug: 'product-196',
    name: 'Assorted Product 196',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Shoes',
    price: 121307,
    brand: 'Aperture',
    images: [{ url: findImage('prod_img_196').url, hint: findImage('prod_img_196').hint }],
    stock: 14,
    rating: 4.5,
    reviewCount: 450
  },
  {
    id: 'prod_197',
    slug: 'product-197',
    name: 'Assorted Product 197',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Watches',
    price: 17095,
    brand: 'Zenco',
    images: [{ url: findImage('prod_img_197').url, hint: findImage('prod_img_197').hint }],
    stock: 104,
    rating: 4.5,
    reviewCount: 301
  },
  {
    id: 'prod_198',
    slug: 'product-198',
    name: 'Assorted Product 198',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Underwear',
    price: 66928,
    brand: 'Stellar',
    images: [{ url: findImage('prod_img_198').url, hint: findImage('prod_img_198').hint }],
    stock: 12,
    rating: 4.6,
    reviewCount: 221
  },
  {
    id: 'prod_199',
    slug: 'product-199',
    name: 'Assorted Product 199',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Clothes',
    price: 147814,
    brand: 'Nexa',
    images: [{ url: findImage('prod_img_199').url, hint: findImage('prod_img_199').hint }],
    stock: 13,
    rating: 4.1,
    reviewCount: 167
  },
  {
    id: 'prod_200',
    slug: 'product-200',
    name: 'Assorted Product 200',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Wigs',
    price: 196887,
    brand: 'Orion',
    images: [{ url: findImage('prod_img_200').url, hint: findImage('prod_img_200').hint }],
    stock: 154,
    rating: 4.6,
    reviewCount: 228
  },
  {
    id: 'prod_201',
    slug: 'product-201',
    name: 'Assorted Product 201',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Laptops',
    price: 179507,
    brand: 'Helios',
    images: [{ url: findImage('prod_img_201').url, hint: findImage('prod_img_201').hint }],
    stock: 166,
    rating: 4.9,
    reviewCount: 381
  },
  {
    id: 'prod_202',
    slug: 'product-202',
    name: 'Assorted Product 202',
    description: 'A brand new high-quality item from our latest collection. Available for redemption now.',
    category: 'Shoes',
    price: 76092,
    brand: 'iDino',
    images: [{ url: findImage('prod_img_202').url, hint: findImage('prod_img_202').hint }],
    stock: 191,
    rating: 4.2,
    reviewCount: 461
  }
];
